### ISSUE TITLE
Welcome message in persistentRStudio is printed using `cat()` instead of `message()`

### ISSUE THREAD

**Issue by calicule** [cloudyr/googleComputeEngineR#100]
Hi, thank you for cloudyr! 

I'm trying to install a package (minqa) which contains in its Makevars:

```
PKG_LIBS = `$(R_HOME)/bin/Rscript -e "Rcpp:::LdFlags()"`
```

When I install this, the welcome message gets added to the linker command as follows:
```
g++ -shared -L/usr/local/lib/R/lib -L/usr/local/lib -o minqa.so altmov.o bigden.o biglag.o bobyqa.o bobyqb.o lagmax.o minqa.o newuoa.o newuob.o prelim.o rescue.o trsapp.o trsbox.o trstep.o uobyqa.o uobyqb.o update.o updatebobyqa.o # Welcome to RStudio Server on Google Compute Engine! Today is Wed Mar 14 18:49:17 2018 -lgfortran -lm -lquadmath -L/usr/local/lib/R/lib -lR
```

Wrapping the welcome message in `message()` rather than `cat()` fixes this problem.

See https://github.com/cloudyr/googleComputeEngineR/pull/99 for a fix.

**Comment by MarkEdmondson1234** [comment]
Thanks very much for the fix!  Unintended consequences of using `cat`, will keep that in mind
