### ISSUE TITLE
Accessing Google Drive from instances

### ISSUE THREAD

**Issue by ctlamb** [cloudyr/googleComputeEngineR#102]
I see a # of functions in `googleComputeEngineR' that may be used to access data in google drive, but I am curious if this downloads data from google's cloud (drive) via the internet, or is somehow more directly linked to these data. The reason I ask is that I have a large spatial dataset (50GB) on google drive, that I need to predict on using a model. However, if I have to download the 50GB onto each instance, it may take far too long, whereas if the instance can read/write using these data directly from the cloud it would make things much easier. So, how does this work, exactly?

**Comment by MarkEdmondson1234** [comment]
Which functions do you refer to?  There are some that point to Google Cloud Storage, but Google Drive is a service (probably built on top of cloud storage)

I guess Google Cloud Storage is better for the large data you refer to, in which case one prime motivation for using a Google VM is that they are close to the cloud storage and takes advantage of Google internal network speeds (make sure in same region and/or project) which are ridiculous - I would test it out to see what the lag is but I guess 50GB should be not a big issue.  Simplest solution I think if it works.  (via `googleCloudStorageR` perhaps) 

However, if it is too slow then next I would look at loading the data onto a VM disk, that in read only mode can be read from several VMs - then in the setup for each VM you attach to that disk (SSD for max performance, but costs more cash) via the `disk_source` argument in `gce_vm()`

**Comment by ctlamb** [comment]
Thanks, Mark! I think I confused Google Cloud Storage with Google Drive, assuming they were the same. No problem. Google Cloud Storage will likely be a good solution. Thanks! Will hopefully be testing in the next few weeks.

**Comment by ctlamb** [comment]
Hi Mark, I've had time to play with this today. When I start up a few instances and try to test run downloading some data using gcs_get_object(), the data seem to download onto my computer, not the instances. What am I missing, do I need to load the googleCloudStorageR package within the instance and gce_auth() or is that automatically done when I build the instances (which is what I assumed, given that I set the default_bucket.


```
##Enviro settings on my computer:
Sys.setenv(GCE_AUTH_FILE = "/Users/clayton.lamb/Google Drive/Documents/University/R_Tricks/Cloud/lambspatialgrid-4f41061a8609.json",
           GCE_DEFAULT_PROJECT_ID="lambspatialgrid",
           GCE_DEFAULT_ZONE="us-west1-a",
           GCS_DEFAULT_BUCKET = "phdrastertiles")

##I start up VM's..ommited here for brevity, then use:
future::plan(cluster, workers = as.cluster(vms))


##The function I send to the VM's is as follows (had some issues with docker again so just load packages in script to start.

predict_chunks <- function(chunk){
  install.packages("survival", dependencies = TRUE)
  library(survival)
  install.packages("gbm", dependencies = TRUE)
  library(gbm)
  install.packages("dismo", dependencies = TRUE)
  library(dismo)
  install.packages("raster", dependencies = TRUE)
  library(raster)
  
  
  ##download raster tiles for chunk
  for(i in 1:length(chunk$name)){
    gcs_get_object(chunk$name[[i]], saveToDisk = str_split(chunk$name[[i]],"/", simplify = TRUE)[,3])
  }
  
  
  ####STACK
  STACK<- raster::stack(list.files(path="", pattern=".tif$"))
  
  
  occ.continuous <-dismo::predict(STACK, a, n.trees = a$gbm.call$best.trees, type="response")
  
  
  return(occ.continuous)
}
```

**Comment by ctlamb** [comment]
As I'm trying to debug this, here is a simpler, reproducible example. Can't seem to get it to work

```

require(googleComputeEngineR)
require(googleCloudStorageR)
require(future)

Sys.setenv(GCE_AUTH_FILE = "/Users/clayton.lamb/Google Drive/Documents/University/R_Tricks/Cloud/lambspatialgrid-4f41061a8609.json",
           GCE_DEFAULT_PROJECT_ID="lambspatialgrid",
           GCE_DEFAULT_ZONE="us-west1-a",
           GCS_DEFAULT_BUCKET = "phdrastertiles")

##Authenticate
gce_auth()
gce_global_project("lambspatialgrid")
gce_global_zone("us-west1-a")



##how many instances?
n=2

## auto auth to GCE via environment file arguments
## create CPUs names
vm_names <- paste0("my-server",1:n)



## start up VMs 
vms <- lapply(vm_names, googleComputeEngineR::gce_vm, 
              predefined_type = "n1-standard-2", 
              template = "r-base")

## add any ssh details, username etc.
vms <- lapply(vms, googleComputeEngineR::gce_ssh_setup)


# use plan(sequential) for local testing
future::plan(future::cluster, workers = future::as.cluster(vms))
#plan(sequential)


## the action you want to perform on the elements in the cluster
predict_chunks <- function(chunk){
 install.packages("googleCloudStorageR", dependencies = TRUE)
 library("googleCloudStorageR")
  
  gcs_global_bucket("phdrastertiles")
  test <-gcs_list_objects()[-chunk,]

  return(test)
}



#parallel
system.time(result2 <- future::future_lapply(1:2, predict_chunks)) 
## tidy up google machines
lapply(vms, FUN = gce_vm_stop)
lapply(vms, FUN = gce_vm_delete)

```

**Comment by MarkEdmondson1234** [comment]
Right, so the authentication is not being enacted on the instances, only locally in the example above.  The `googleCloudStorage` calls need to be authenticated on the instances as they are in a separate environment.  For this it should just need a call to `googleAuthR::gar_gce_auth()` as this will authenticate with the metadata available to each VM, and should give you access to all cloud resources (including Cloud Storage) in the same project.  It uses the `default`service key. 

Also consider that `GCS_DEFAULT_BUCKET = "phdrastertiles")` is currently only local R, not on VM.

**Comment by ctlamb** [comment]
OK that makes sense.

Should I remove `GCS_DEFAULT_BUCKET = "phdrastertiles"`?

I have updated code as follows, by adding `googleAuthR::gar_gce_auth()` but now get the following error `Error: there is no package called ‘googleCloudStorageR’` despite the package loading being the first step?

```
###########################################################
##TEST##
##SET UP PARALLEL PROCESSING WITH GOOGLE API FOR BUCKET
###########################################################
require(googleComputeEngineR)
require(googleCloudStorageR)
require(future)

Sys.setenv(GCE_AUTH_FILE = "/Users/clayton.lamb/Google Drive/Documents/University/R_Tricks/Cloud/lambspatialgrid-4f41061a8609.json",
           GCE_DEFAULT_PROJECT_ID="lambspatialgrid",
           GCE_DEFAULT_ZONE="us-west1-a",
           GCS_DEFAULT_BUCKET = "phdrastertiles")

##Authenticate
gce_auth()
gce_global_project("lambspatialgrid")
gce_global_zone("us-west1-a")
gcs_global_bucket("phdrastertiles")


##how many instances?
n=2

## auto auth to GCE via environment file arguments
## create CPUs names
vm_names <- paste0("my-server",1:n)



## start up VMs 
vms <- lapply(vm_names, googleComputeEngineR::gce_vm, 
              predefined_type = "n1-standard-2", 
              template = "r-base")

## add any ssh details, username etc.
vms <- lapply(vms, googleComputeEngineR::gce_ssh_setup)


# use plan(sequential) for local testing
future::plan(future::cluster, workers = future::as.cluster(vms))
#plan(sequential)


## the action you want to perform on the elements in the cluster
predict_chunks <- function(chunk){
  install.packages("googleCloudStorageR", dependencies = TRUE)
  library(googleCloudStorageR)
  googleAuthR::gar_gce_auth()
  
  gcs_global_bucket("phdrastertiles")
  test <-gcs_list_objects()[-chunk,]
  
  return(test)
}



#parallel
system.time(result2 <- future::future_lapply(1:2, predict_chunks)) 



## tidy up google machines
lapply(vms, FUN = gce_vm_stop)
lapply(vms, FUN = gce_vm_delete)

```

**Comment by MarkEdmondson1234** [comment]
> Should I remove GCS_DEFAULT_BUCKET = "phdrastertiles"?

Its not necessary for this it seems, as it will only by used for local functions.

> I have updated code as follows, by adding googleAuthR::gar_gce_auth() but now get the following error Error: there is no package called ‘googleCloudStorageR’ despite the package loading being the first step?

Hmm, perhaps put a conditional for `require(googleCloudStorageR)` which will return `TRUE` if its loaded successfully, but the best practice would be to make sure this package is installed via the Dockerfile its running on.

**Comment by Gibbsdavidl** [comment]
Suppose I start a Rstudio server VM, and log into web interface.  Once I'm in R, running in the VM, what is the best/easiest way to access a bucket (non-public)? Thanks!!

Using gar_gce_auth() works great after logging into an Rstudio instance. Thanks!
User error: I had strayed away from my home dir and didn't have permissions to write the token. doh!

**Comment by MarkEdmondson1234** [comment]
Easiest is to use `googleCloudStorageR`, `gar_gce_auth()` for authentication (reuses existing auth) and read from the buckets in the same Google Cloud project.  An example can be seen [here](https://cloudyr.github.io/googleComputeEngineR/articles/scheduled-rscripts.html).
