### ISSUE TITLE
Installing VM's with libcurl 

### ISSUE THREAD

**Issue by nbarsch** [cloudyr/googleComputeEngineR#103]
Pardon the fact that I'm a bit new with googlecomputeenginer and docker. 

I'm trying to use googlecomputeenginer to launch a cluster of VM's to run bigrquery. I have not used docker before and have tried extensively to get a docker image from containerit to work custom as well as create the VM's from the r-devel template that looks like it has libcurl installed: https://hub.docker.com/r/rocker/r-devel/~/dockerfile/

My problem is when I set up the cluster and try to install bigrquery (or httr or curl) I get the following:

```
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Using PKG_CFLAGS=
Using PKG_LIBS=-lcurl
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libcurl was not found. Try installing:
 * deb: libcurl4-openssl-dev (Debian, Ubuntu, etc)
 * rpm: libcurl-devel (Fedora, CentOS, RHEL)
 * csw: libcurl_dev (Solaris)
If libcurl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libcurl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘curl’
* removing ‘/usr/local/lib/R/site-library/curl’
```

How do I install libcurl4 on the VM's while either setting up the cluster or using an install after the cluster has been set up? Thank you very much for your help!

**Comment by MarkEdmondson1234** [comment]
You may be better off starting from rocker/tidyverse or one of the public gcr.io/gcer-public images in your FROM field as that will have installed some more dependencies for you. 

If you still need custom Dockerfile image see the website for some workflows building your own - I recommend the package containerit too as you can point that at your script and it will build the Dockerfile for you with all dependencies needed.  Let me know how it goes and if struggling leave some code and what code you have here and we will try point in right direction.
