### ISSUE TITLE
Error writing to connection

### ISSUE THREAD

**Issue by ctlamb** [cloudyr/googleComputeEngineR#105]
I am running a routine on 4 instances (using `future_lapply()`), which had previously worked fine but now seems to throw the following error:

`Error in serialize(data, node$con) : error writing to connection`

I last ran on a different wifi connection, but this connection seems to work fine and the VM's start up as expected.

What's going on here?

**Comment by MarkEdmondson1234** [comment]
Is it possible it’s running out of disk space somewhere? Or file permissions being changed?

**Comment by ctlamb** [comment]
I'm using a "n1-standard-2" instance, which has 7.5GB of memory and what seems to be many TB of space (https://cloud.google.com/compute/docs/machine-types)

I am sending each instance ~10MB of data to use, loading a couple packages, running a model that ends up being <50MB of size.

So I don't think I should be running out of space. And there are no files loaded as I am sending the data with the function for this one.

**Comment by ctlamb** [comment]
Weird..And now it's working...With nothing changed...will monitor and try to find bug if the issue returns..

**Comment by ctlamb** [comment]
I seem to keep having issues. I can run my required projects in small batches by reducing the datasize I send to each instance, which also reduces the time the instances are running, but when I try to scale up to the full data I keep getting these type of errors. Any thoughts?

It must be a wifi issue? 

<a href="https://ibb.co/eq1mhy"><img src="https://preview.ibb.co/fFtMFJ/Screen_Shot_2018_06_12_at_10_47_18_AM.png" alt="Screen Shot 2018 06 12 at 10 47 18 AM" border="0" /></a>

**Comment by ctlamb** [comment]
As a followup, I have ran this 3x more, and the script seems to always fail after ~8,100-8,400 seconds, which means its unlikely to be my connection but something happening internally. Seeing as it works on a smaller batch of data I am thinkings its a memory issue perhaps? It's very odd though, seeing as this was working a month ago.

**Comment by MarkEdmondson1234** [comment]
I am following this, mulling over what i could be - that is a clue, that perhaps your SSH session is timing out.  This may be something @HenrikBengtsson may be able to help with as it sounds like the future session is timing out. I guess there must be a way to renew the connection.

**Comment by HenrikBengtsson** [comment]
Hi. First of all, my best guess is that the origin of:
```
Error in serialize(data, node$con) : error writing to connection
```
is:
```r
> parallel:::sendData.SOCKnode
function (node, data) 
serialize(data, node$con)
<bytecode: 0x25cf198>
<environment: namespace:parallel>
```

The most likely reason I can see for this is that the connection went down and when the master process tries to _send_ information to the worker (the cluster node) we get that error.  It could be that the worker crashed and thereby closing the connection and then the master process tries to set up a new future for that crashed worker, it fails.  We should be able to narrow down in exactly what step this occurs if you turn on debugging, i.e.
```r
options(future.debug = TRUE)
```
This will produce lots of output, but when you get the error the last 10-100 lines should contain clues about where it happens.  If it occurs when a new future is set up/launched, then that is very useful information for figuring out the next step.

What would also help is if you gather more traceback information when the error occurs. You can add the following to your local `~/.Rprofile` - this should work when running R in interactive and non-interactive mode:
```r
options(error = function() {
  tb <- .traceback(2L)
  name <- getOption("startup.session.dumpto", "last.dump")
  utils::dump.frames(dumpto = name, to.file = FALSE)
  save(list = name, envir = .GlobalEnv, file = paste0(name, ".rda"))
  dumpto <- get(name, envir = .GlobalEnv)
  rm(list = name, envir = .GlobalEnv)
  sink(file = paste0(name, ".out"))
  on.exit(sink(NULL))
  
  cat("** Traceback:\n")
  print(tb)

  cat("\n** Dumped frames:\n")
  print(dumpto)
})
```


# Some more troubleshooting

It could be that there went to long time between master and node communicated and we'd get a socket connection timeout.  However, the default to `getOption("future.makeNodePSOCK.timeout", 30 * 24 * 60 * 60)`, which is 30 days >> 8400 seconds.  Also, if that would be the case, it looks like we'd get another type of error message:

```r
library(future)
cl <- makeClusterPSOCK(1L, timeout = 3L)
plan(cluster, workers = cl)
f <- future(42)
print(value(f))
Sys.sleep(5L) ## Let connection timeout
f <- future({ pi })
Warning in .Internal(lapply(X, FUN)) :
  closing unused connection 4 (<-localhost:11131)
Error in unserialize(node$con) : error reading from connection
```
This one complains about "reading from" not "writing to", which means it happens in a different part of the code.

If we play the game of terminating the worker without the future framework knowing, we get:
```r
library(future)
cl <- makeClusterPSOCK(1L)
plan(cluster, workers = cl)
f <- future(42)
print(value(f))

## Force worker to shut down
parallel:::stopNode(cl[[1]])

f <- future(42)
## Error in summary.connection(connection) : invalid connection
```

My best guess is that the worker crashes or, as @MarkEdmondson1234 says a timeout at the SSH level (which I have zero experience with/knowledge about).

**Comment by MarkEdmondson1234** [comment]
Thanks so much for the exhaustive comment @HenrikBengtsson !

Another thing to consider is the script @ctlamb is passing - if its installing packages within the script (as I saw from another issue), it could be this process takes too long, in which case I would work with the Docker image to make it as "ready" as possible to have the script finish in good time.

**Comment by ctlamb** [comment]
Hi guys, thanks again for all the help here. I added `options(future.debug = TRUE)` to my local session as well as the updated .Rprofile info, re-ran and this is what I got, which I don't think is the 10-100 lines of code @HenrikBengtsson was referring to but the  `length: X (resolved future X)
` is new to me and must be from this options() call.
```
 length: 3 (resolved future 3)
 length: 2 (resolved future 4)
packet_write_wait: Connection to 35.230.26.119 port 22: Broken pipe
 length: 1 (resolved future 1)
packet_write_wait: Connection to 35.233.155.213 port 22: Broken pipe
 length: 0 (resolved future 2)
resolve() on list ... DONE
Error in unserialize(node$con) : 
  Failed to retrieve the value of ClusterFuture from cluster node #1 (on ‘35.230.26.119’).  The reason reported was ‘error reading from connection’
```

**Comment by ctlamb** [comment]
@MarkEdmondson1234 I'm happy to get this going on a docker. That is undoubtedly a better way to do it. After our issues getting my raster docker to work on my account, and having to get you to host it, I was hesitant to create a new docker for this work. I am not very familiar with the language used in the docker so it is a bit prohibitive at times.

Would this work as the docker to load the packages that I am loading within the current function:

So replace this:

```
 install.packages("survival", dependencies = TRUE)
  library(survival)
  install.packages("gbm", dependencies = TRUE)
  library(gbm)
  install.packages("dismo", dependencies = TRUE)
  library(dismo)
```

 With this docker? Which I can load the same way we worked through [here ](https://github.com/cloudyr/googleComputeEngineR/issues/93), once I load it up. But does this load dependencies too?
```
FROM rocker/tidyverse
MAINTAINER Clayton Lamb 

# install R package dependencies
RUN apt-get update && apt-get install -y \
    ## clean up
    && apt-get clean \ 
    && rm -rf /var/lib/apt/lists/ \ 
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds
    
## Install packages from CRAN
RUN install2.r --error \ 
    -r 'http://cran.rstudio.com' \
    googleAuthR \ 
    googleComputeEngineR \ 
    survival \
    gbm \
    dismo \
    && rm -rf /tmp/downloaded_packages/ /tmp/*.rds \
```

**Comment by MarkEdmondson1234** [comment]
Hi @ctlamb - yes the Dockerfile look equivalent.  That will load any R package dependencies but not linux dependencies, so you can either build, wait for it to fail, read the error on what linux dependency is needed (if any) and then add those after the `apt-get install` line or make a minimal R script that loads your required libraries at the top, then run `containerit` over it which should find them for you.
