### ISSUE TITLE
Greta VM?

### ISSUE THREAD

**Issue by ignacio82** [cloudyr/googleComputeEngineR#108]
Is there an example for running greta with google ComputeEngineR?

I tried running this one

https://hub.docker.com/r/earthlab/r-greta/

But it is not working for me

**Comment by MarkEdmondson1234** [comment]
Not seen that one!  Can I see what you tried?  I think in theory looking at the open ports this should be close:

```r
vm <- gce_vm(name = "rstudio-greta",
              template = "rstudio",
              dynamic_image = "earthlab/r-greta",
              username = "me", password = "mypassword")
```

**Comment by ignacio82** [comment]
I think the problem is that the username has to be "rstudio". If you look at [this](https://hub.docker.com/r/earthlab/r-tensorflow/~/dockerfile/) dockerfile, it installs tensorflow for the rstudio user. I tried setting `username = "rstudio"` and it does not work. I also tried setting `username = "me"` and running `tensorflow::install_tensorflow()` after the fact, but that did not work either.

**Comment by ignacio82** [comment]
@MarkEdmondson1234 [it looks](https://github.com/earthlab/dockerfiles/issues/6#issuecomment-395784314) like the only way to use that docker image is with the rstudio user, which I think is not allowed with `gce_vm`. Is that correct? is there a workaround?

**Comment by MarkEdmondson1234** [comment]
Yes to use `gce_vm_container` instead, which is what `gce_vm()`calls underneath, or to modify and build the Dockerfile of `r-greta` to your own that modifies the username itself.   

I'm not sure why the username is the problem, I would argue its bad security in the `r-greta` file to have it set and not changeable, but would need to take a look at its own Dockerfile to see whats going on.

**Comment by ignacio82** [comment]
I'm not sure why but I cannot install tensorflow if I launch the vm with another user. [This](https://github.com/rstudio/tensorflow/issues/256#issuecomment-402185008) is the error I get:

```
> tensorflow::install_tensorflow()
Creating virtualenv for TensorFlow at  ~/.virtualenvs/r-reticulate
Already using interpreter /usr/bin/python
New python executable in /home/ignacio/.virtualenvs/r-reticulate/bin/python
ERROR: The executable /home/ignacio/.virtualenvs/r-reticulate/bin/python could not be run: [Errno 13] Permission denied
Error: Error 100 occurred creating virtualenv at ~/.virtualenvs/r-reticulate
Execution halted
```
I also tried to create a dockerfile that installs tensorflow for my user, but it did not work either:

```
FROM earthlab/r-greta
LABEL maintainer="Ignacio Martinez <ignacio@protonmail.com>"

RUN useradd ignacio \
  && echo "ignacio:ignacio" | chpasswd \
	&& mkdir /home/ignacio \
	&& chown ignacio:ignacio /home/ignacio \
	&& addgroup ignacio staff 
	

USER ignacio

RUN R -e "tensorflow::install_tensorflow()"

USER root

RUN install2.r --error \
  googleComputeEngineR googleCloudStorageR \
  secret \
  drat \
  mvtnorm \
  loo \
  rmarkdown \
  caTools \
  bitops

RUN Rscript -e "devtools::install_github(c('rmcelreath/rethinking'))" 

RUN rm -rf /tmp/downloaded_packages/ /tmp/*.rds
```

**Comment by MarkEdmondson1234** [comment]
I have a running Tensorflow RStudio now using the image gcr.io/gcer-public/rstudio-keras - guide to follow

**Comment by MarkEdmondson1234** [comment]
Will track this in #101
