### ISSUE TITLE
Specifying subnetworks when you create a new VM

### ISSUE THREAD

**Issue by avidalfinsa** [cloudyr/googleComputeEngineR#110]
When you create a new VM with `gce_vm `or `gce_vm_create `it is possible to define the network to use.

```
vm <- gce_vm(template = "rstudio", 
             name = "rstudio-server", 
             predefined_type = "f1-micro",
             network = "mynetwork",
             username = "rstudio", 
             password = "rstudio1234")
```
The problem is when you have defined subnetworks of this network because it returns an error like this:

```
2018-08-08 12:01:35> Creating template VM
Request failed [400]. Retrying in 1.2 seconds...
Request failed [400]. Retrying in 1.9 seconds...
2018-08-08 12:01:39> Request Status Code: 400
Scopes: https://www.googleapis.com/auth/cloud-platform
Method: service_json
Error: API returned: Invalid value for field 'resource.networkInterfaces[0]': ''. Subnetwork should be specified for custom subnetmode network
```

How is it possible to define the subnetwork to attach this VM to?

My subnetworks are like this:

```
  "network": "projects/myproject/global/networks/mynetwork",
  "privateIpGoogleAccess": false,
  "region": "projects/myproject/regions/europe-west1",
  "selfLink": "projects/myproject/regions/europe-west1/subnetworks/mysubnetwork"
```

**Comment by MarkEdmondson1234** [comment]
I've not come across this before so will need to check, I think the [network interface part of the API ](https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert) has updated since the implementation below, so will look to update it.

https://github.com/cloudyr/googleComputeEngineR/blob/df059e8b9433a7368a708285abb060de0c891700/R/networks.R#L36-L65

**Comment by MarkEdmondson1234** [comment]
This should be fixed now in latest github version https://github.com/cloudyr/googleComputeEngineR/issues/154
