### ISSUE TITLE
transfer files via scp

### ISSUE THREAD

**Issue by rpgit12** [cloudyr/googleComputeEngineR#115]
I'm trying to transfer files to an rstudio instance using scp:

> gcloud compute scp test.txt rstudio:/home/speedy/

but am getting Connection refused - both for SCP & SSH.

ssh: connect to host xxx.xxx.xxx.xxx port 22: Connection refused

I can connect to the container from the web console, but am unable to connect to the instance. Any thoughts?

I checked firewall rules and they seem to be fine.

**Comment by rpgit12** [comment]
Just came across the recommendation to use googleCloudStorageR. Closing this issue.

**Comment by MarkEdmondson1234** [comment]
Yes, this request came at the same time :)
