### ISSUE TITLE
How to change "limit-file-upload-size-mb" for the created RStudio Server

### ISSUE THREAD

**Issue by abhijith-asok** [cloudyr/googleComputeEngineR#118]
Hey there,

Firstly, thanks for the package. Very convenient. I used the package to create an RStudio Server on my Google Cloud and it seems to be running smoothly. However, whenever I try to upload some heavy files onto the server, it seems to limit me at 2 GB for some reason. Upon Googling, I found that "limit-file-upload-size-mb" can be reset to change that limit, but I am unsure as to where and how in the gce_vm() command I can mention that, if at all I can. Please let me know if there is a way to do it. I am on a deadline and this is pretty much the only obstacle standing in my way. Thanks!

**Comment by MarkEdmondson1234** [comment]
I recommended to use googleCloudStorageR in your script and upload/download your data from cloud storage in your script instead of uploading it manually. It’s much better long term as you can then scale to other VMs. The authentication of the bucket if in the same project is easy too, use gar_gce_auth()

**Comment by abhijith-asok** [comment]
Thanks! I considered that, but the files I am looking at are .gds files for which I am yet to find a command that would read it in from a web link. That's the reason why I was looking them uploaded into server storage. I saw the FUSE can be used to have the google bucket appear as a subdirectory in the server, which would be the most convenient option, but I could not find a good tutorial that outlines the steps to do that specifically in an RStudio Server setting. I found a general guide, but that wasn't clear enough for me at all and I was lost. Do you have any recommendations on how to get this done / links to documents that can help with this? TIA!

**Comment by MarkEdmondson1234** [comment]
I think you will find FUSE quite complicated to set up.  Google cloud storage is just a binary file store, so you can upload any types of files to it - it doesn't use web links.  In practice in your code it would be adding:

```r
library(googleAuthR)
library(googleCloudStorgaeR)

gar_gce_auth()
gce_get_object("the_file.gds", bucket = "your-bucket", saveToDisk="filename.rds")

...do the code that works with filename.rds as you would locally
```

A lot of the examples on the website do similar, like this one: https://cloudyr.github.io/googleComputeEngineR/articles/persistent-rstudio.html#using-googlecloudstorager

**Comment by abhijith-asok** [comment]
Those examples seem to get the work done. Can't believe I have been stuck on this overnight. Thank you so much!

**Comment by MarkEdmondson1234** [comment]
Cool glad it is working, I think it is the simplest solution once you get the hang of it :)  And also mean you have infinite scale when you need it.

**Comment by abhijith-asok** [comment]
Hey,

Thanks a lot for the help so far. I have unfortunately run into something weird after I got this working. The file transfer happened without problems, but after this, it looks like I am not able to install any package on the RServer. Whenever I try to install any package, it just stops installation midway and then I am met with the following message:

`# Welcome Ignacio! Today is  Sun Dec 16 21:18:23 2018 
Error in loadNamespace(name) : 
  there is no package called ‘googleCloudStorageR’
Calls: .First ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted`

This is irrespective of which package I try to install. This did not exist previously, prior to trying to get the gds files on the server. Why is this occurring? Did something get messed up while setting it up?
