### ISSUE TITLE
 Cannot authenticate

### ISSUE THREAD

**Issue by AlexKost5791** [cloudyr/googleComputeEngineR#119]
Dear GoogleComputeEngineR developers,
I followed all instructions explained under this link:
https://cloudyr.github.io/googleComputeEngineR/articles/installation
ran script ( some information substituted  with XXX"

#**********
Set up*************
library(googleComputeEngineR)
project <- "My_project"
zone <- "northamerica-northeast1-b"
account_key <- "xxxxxxxxxxxx"
Sys.setenv(GCE_AUTH_FILE=account_key,
           GCE_DEFAULT_PROJECT_ID=project,
           GCE_DEFAULT_ZONE=zone)
gce_auth()
#*****************
R studio console populated the following:

Error in googleAuthR::gar_auto_auth(required_scopes, new_user = new_user,  : 
  Cannot authenticate - options(googleAuthR.scopes.selected) needs to be set to includehttps://www.googleapis.com/auth/cloud-platform or https://www.googleapis.com/auth/compute
In addition: Warning message:
In googleAuthR::gar_auto_auth(required_scopes, new_user = new_user,  :
  travis_environment_var argument is now unsupported and does nothing

Please, help , advice.
Please, also note that I've already run instances on GCP with no issues.

Thank you,
Alex K

**Comment by MarkEdmondson1234** [comment]
Download the authentication file via JSON instead of using `gce_auth()` and use auto-authentication - instructions further down the page you linked to ( https://cloudyr.github.io/googleComputeEngineR/articles/installation-and-authentication.html#auto-authentication-via--renviron )

**Comment by JacoVos** [comment]
Dear Mark,

I  am struggling to solve the following error:

Error: gce_auth() is defunct.  Authenticate instead by downloading your JSON key and placing in a GCE_AUTH_FILE environment argument.  See https://cloudyr.github.io/googleComputeEngineR/articles/installation-and-authentication.html or vignette('installation-and-authentication', package = 'googleComputeEngineR')

I am fairly new to Rstudio so the issue might only be a minor fix.  I fllowed this li you created https://code.markedmondson.me/launch-rstudio-server-google-cloud-in-two-lines-r/.
However, whether or not I set my variables in my .Renviron file, or use Sys.setenv() method, the same error occurs.
Might be the auth file path? I downloaded the json key file which I saved in my project directory. 

`library(googleComputeEngineR)
project <- "myProjectID"
zone <- "us-east1-c"
account_key <- "*.json"

Sys.setenv(GCE_AUTH_FILE = account_key,
           GCE_DEFAULT_PROJECT_ID = project,
           GCE_DEFAULT_ZONE = zone)

gce_auth()`

Session info: 
`R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_South Africa.1252  LC_CTYPE=English_South Africa.1252   
[3] LC_MONETARY=English_South Africa.1252 LC_NUMERIC=C                         
[5] LC_TIME=English_South Africa.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] usethis_1.5.0              googleComputeEngineR_0.3.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0        codetools_0.2-15  listenv_0.7.0     future_1.13.0     digest_0.6.19    
 [6] assertthat_0.2.0  R6_2.3.0          jsonlite_1.6      neuralnet_1.44.2  httr_1.4.0       
[11] rlang_0.3.1       curl_3.3          fs_1.3.1          googleAuthR_0.7.0 tools_3.5.2      
[16] glue_1.3.0        parallel_3.5.2    compiler_3.5.2    askpass_1.1       globals_0.12.4   
[21] memoise_1.1.0     openssl_1.4`

Would much appreciate your help!

**Comment by MarkEdmondson1234** [comment]
You need to specify the environment arguments before the library is loaded.   

Restart R in-between yourself adding the file path to the environment argument via an `.Renviron` file.   You should be able to see the file path to your JSON when you use `Sys.getenv("GCE_AUTH_FILE")` in R

If you do want to set them in code, you need to create the environment args before loading the library, but the intended useage is to put them in an `.Renviron`

```r

project <- "myProjectID"
zone <- "us-east1-c"
account_key <- "*.json"

# this needs to be set before you load the library.  
# The intended usage is to put them in an `.Renvion` file, not specify them in code
Sys.setenv(GCE_AUTH_FILE = account_key,
GCE_DEFAULT_PROJECT_ID = project,
GCE_DEFAULT_ZONE = zone))

library(googleComputeEngineR)
```

**Comment by JacoVos** [comment]
Got it! 
Thanks alot for the response!

**Comment by hosseinv** [comment]
Dear Mark,

Based on your directions, I created .Renviron file and located it in my Rstudio workspace folder. The content of the file is as follows (some details were substituted by xxxx)

GCE_AUTH_FILE="/DATA/MODELING/batching_analysis/cloud/xxxx.json"
GCE_DEFAULT_PROJECT_ID="xxxx"
GCE_DEFAULT_ZONE="asia-northeast1-a"

I saved the file and restarted the  Rstudio and I ran this code:


project="xxxx"
zone="asia-northeast1-a"
account_key="DATA/MODELING/batching_analysis/cloud/xxxx.json"
Sys.setenv(GCE_AUTH_FILE=account_key,
           GCE_DEFAULT_PROJECT_ID=project,
           GCE_DEFAULT_ZONE=zone)

library(googleComputeEngineR)

and then I got the following error:

Setting scopes to https://www.googleapis.com/auth/cloud-platform
Failed! Auto-authentication via DATA/MODELING/batching_analysis/cloud/xxxx.json - error was: 
Set default project ID to 'xxxx'
Set default zone to 'asia-northeast1-a'
Warning message:
package ‘googleComputeEngineR’ was built under R version 3.5.3 

So, I would be grateful if you can guide me on how to solve this.

Thank you!

**Comment by MarkEdmondson1234** [comment]
What happens when you run `googleAuthR::gar_auth_service("DATA/MODELING/batching_analysis/cloud/xxxx.json")` - given above it should error and give you a message why to help pin it down.  Perhaps wrong json file or location?

**Comment by hosseinv** [comment]
Thank you for your prompt reply.

 [I changed "account_key into "account_key" in the code:]

> googleAuthR::gar_service_auth("account_key"="DATA/MODELING/batching_analysis/cloud/xxxx.json")

I got this message: 
Error: 'gar_service_auth' is not an exported object from 'namespace:googleAuthR'

thanks

**Comment by MarkEdmondson1234** [comment]
Sorry its `googleAuthR::gar_auth_service()`

**Comment by MarkEdmondson1234** [comment]
And I copy-paste too much, run this:

`googleAuthR::gar_auth_service("DATA/MODELING/batching_analysis/cloud/xxxx.json")`

**Comment by hosseinv** [comment]
I got this:

Error in init_oauth_service_account(self$secrets, scope = self$params$scope,  : 
  Bad Request (HTTP 400).

**Comment by hosseinv** [comment]
I got this:

Error in init_oauth_service_account(self$secrets, scope = self$params$scope, :
Bad Request (HTTP 400).

**Comment by MarkEdmondson1234** [comment]
Hmm well that suggests no scopes set etc.  What version are you running? `sessionInfo()` - use the CRAN versions as a basis, the auth in googleAuthR on dev is experimental at the moment. 

Then start a new R session and start again - something weird going on with scopes not being set? Check what `getOption("googleAuthR.scopes.selected")` states.

**Comment by hosseinv** [comment]
i am using the latest version:

> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8.1 x64 (build 9600)

**Comment by MarkEdmondson1234** [comment]
I need the rest of the output of `sessionInfo()`, checking the loaded package versions are CRAN

**Comment by hosseinv** [comment]
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8.1 x64 (build 9600)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googleComputeEngineR_0.3.0

loaded via a namespace (and not attached):
 [1] codetools_0.2-15  listenv_0.7.0     future_1.14.0     packrat_0.5.0     digest_0.6.18     assertthat_0.2.0  R6_2.3.0          jsonlite_1.5     
 [9] httr_1.4.1        curl_3.2          googleAuthR_0.8.1 tools_3.5.0       parallel_3.5.0    compiler_3.5.0    globals_0.12.4    memoise_1.1.0    
[17] openssl_1.1      
> 
> 
> 
> getOption("googleAuthR.scopes.selected")
[1] "https://www.googleapis.com/auth/cloud-platform"
