### ISSUE TITLE
topicmodels package does not install

### ISSUE THREAD

**Issue by doritge** [cloudyr/googleComputeEngineR#121]
Hi,
trying to install topicmodels package via RStudio server running on instance installed with rstudio template. Get the following message:

gcc -I"/usr/local/lib/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c ctm.c -o ctm.o
ctm.c:29:25: fatal error: gsl/gsl_rng.h: No such file or directory
 #include <gsl/gsl_rng.h>
                         ^
compilation terminated.
/usr/local/lib/R/etc/Makeconf:162: recipe for target 'ctm.o' failed

-----------------------------------------
Package maintainer Bettina Gruen that there is a system requirement for:  GNU Scientific Library version >= 1.8, C++11, which must be enabled.
BTW: there is a similar open issue on stackoverflow
Please advise

Dorit

**Comment by MarkEdmondson1234** [comment]
This is not really specific to `googleComputeEngineR`, but it looks like you need to install a dependency first in the terminal (do it there first to see if it works) and you should then move that into the Dockerfile you launch.
