### ISSUE TITLE
Attach SSH login details to the VM object to ensure correct setup.

### ISSUE THREAD

**Issue by MarkEdmondson1234** [cloudyr/googleComputeEngineR#13]
Else it starts a whole line of pain, for instance running harbor::containers() too soon uploads an incorrect SSH key.

**Comment by MarkEdmondson1234** [comment]
Use `Sys.info()[["name"]]` for default SSH username?

**Comment by HenrikBengtsson** [comment]
FYI, parallel pkg uses `Sys.info()[["name"]]` as the default.

Unfortunately, it cannot be undone / set to NULL which has other consequences, cf. https://github.com/HenrikBengtsson/Wishlist-for-R/issues/31.

**Comment by MarkEdmondson1234** [comment]
I think I'll set `Sys.info()[["name"]]` as the default but let it be overidden if needed, but thanks for the note as this may affect `future` calls.

**Comment by HenrikBengtsson** [comment]
Just to clarify future (>= 1.1.0) works around this issue, but if one uses `parallel::makeCluster()` the SSH user is always set.  My comment was just an FYI and that you should allow for `user = NULL` too.

**Comment by MarkEdmondson1234** [comment]
Best idea is to attach the SSH login details to the VM object rather than a global in the package, to cover those situations where different SSH details are needed for different instances.

**Comment by MarkEdmondson1234** [comment]
This is much easier to deal with.
