### ISSUE TITLE
Cannot Interact with VMs from rstudio, macOS

### ISSUE THREAD

**Issue by CMLennon** [cloudyr/googleComputeEngineR#132]
**Describe the bug**
The issue I am having is that, from within RStudio, trying to create a cluster of three super basic one-core vms (using the as.cluster method) is failing due to timeout. As far as I can tell, the issue isn't from the clustering itself, as I have tried running the clustering method using only one virtual machine and the timeout error still occurs. 
The odd thing is that I can create the vms from within Rstudio, delete them from within Rstudio, and I can ssh into them using terminal, but clustering them returns the timeout.

**To Reproduce**
I was following the following instructions, using a super simple function called slow.

```
vm_names <- c("vm1","vm2","vm3")

## Create the cluster using the default template for rocker/r-base
## The this lapply loop starts the job of creating each VM in background
jobs <- 
  lapply(
    vm_names, 
    function(x) {
      gce_vm(
        name = x,
        template = "r-base",
        predefined_type = "g1-small", 
        wait = FALSE ## Don't wait for each job to finish until start the next 
        )
      })

lapply(jobs, gce_wait)
```
Then I build a group of vms
`vms <- lapply(vm_names, gce_vm)`

Then I try to cluster:

```
rshlogfile = TRUE
library(tictoc)
library(future.apply)

plan(cluster, workers = as.cluster(vms[1]))

tic()
future_cluster <- future_lapply(1:15, slow_func)
toc()
```
Then I get an error here, at the 'plan' line.

This looks like:

`Error in socketConnection("localhost", port = port, server = TRUE, blocking = TRUE, : Failed to launch and connect to R worker on remote machine ‘correct-ip’ from local machine ‘mymachine.local’. * The error produced by socketConnection() was: ‘reached elapsed time limit’ (which suggests that the connection timeout of 120 seconds (argument 'connectTimeout') kicked in)...`

**Expected behavior**

```
# library(tictoc) ## For timing. Already loaded.
# library(future.apply) ## Already loaded.

plan(cluster, workers = as.cluster(vms)) 
```

`## 25.987 sec elapsed`

**Screenshots**
Proof I can log into VM built in rstudio:
<img width="487" alt="lookididit" src="https://user-images.githubusercontent.com/46403469/54048846-be478e00-418f-11e9-8270-876332fb6ace.png">

**Session Info**
```
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] future.apply_1.1.0              future_1.11.1.1                 tictoc_1.0                     
[4] googleComputeEngineR_0.2.0.9001

loaded via a namespace (and not attached):
 [1] codetools_0.2-15       listenv_0.7.0          digest_0.6.18          assertthat_0.2.0       R6_2.4.0              
 [6] jsonlite_1.6           httr_1.4.0             curl_3.3               remotes_2.0.2          googleAuthR_0.7.0.9000
[11] tools_3.5.2            xfun_0.5               yaml_2.2.0             parallel_3.5.2         compiler_3.5.2        
[16] askpass_1.1            globals_0.12.4         memoise_1.1.0          openssl_1.2.2          knitr_1.21          
```  

**Additional context**
Thanks for the help!

**Comment by MarkEdmondson1234** [comment]
Have you checked you can SSH into the machines first?  You need to make sure the SSH keys are in the right place, right username used etc.  It needs valid SSH keys that will be uploaded to all the VMs, which in turn will be used to launch docker.

**Comment by MarkEdmondson1234** [comment]
Sorry I now see you have SSH successfully. Can you run the [example for forecasting a large dataset](https://cloudyr.github.io/googleComputeEngineR/articles/massive-parallel.html#forecasting-a-large-data-set) on the website or is it the same issue?

**Comment by CMLennon** [comment]
Well running through the demo one piece at a time, I fail when I hit the 'plan' step here:

```{r}
plan(cluster, workers = as.cluster(vms))
```
However if running it on the custom docker image is what you're looking for to change the error then I'm not sure.

I spent some time today trying to set up a google build trigger docker image, but  I haven't gotten far on how to do that yet, so I'll let you know when I have that part up and running.

Thanks for the quick response!

**Comment by MarkEdmondson1234** [comment]
The custom R image is usually necessary as long running tasks don't run in base R, but its not necessarily the reason for your error:

If you can run this successfully:

```
## names for your cluster - just three for this example
vm_names <- c("vm1","vm2","vm3")
...
                     
## set up SSH for the VMs
vms <- lapply(vms, gce_ssh_setup)  # set any settings necessary here for SSH     

lapply(vms, function(x){
  gce_ssh(vm, paste("echo", x$name, "ssh working"))
})
```

Then everything should be in place `googleComputeEngineR` wise, in which case it may be better to get help from the `future` GitHub issues to help with the diagnose steps.

**Comment by MarkEdmondson1234** [comment]
It could also be that the image is taking too long to install `future` which it needs to do on the cluster - a small cluster may not have enough umph to get it installed within 120 seconds timeout.  Perhaps try an image with `future` installed already (`henrikbengtsson/r-parallel`), or a bigger instance.

**Comment by CMLennon** [comment]
Ok, so I tried two approaches to take those last two suggestions into account. I used the image with the future install already done, and I had one slight modification to the error. Before timing out, I see:

`External IP for instance vm1 : IP-address
connor@Ip-address: Permission denied (publickey).`

with the 'IP-address' part being a correctly identified IP. 

However, your first test suggestion (from two comments ago) worked, but it threw the man-in-the-middle attack warning, saying the host key changed, and told me that all three vms had permission denied. If you think it's a future issue I can open up an issue there

Thank you for your help and patience.

```
connor@IP-address-for-vm Permission denied (publickey).

@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @...
```

**Comment by MarkEdmondson1234** [comment]
The remote host id is when the ip addresses of the VMs have hanged between your setup and your connection, I think if you started with fresh VMs then it will not be there.

**Comment by CMLennon** [comment]
Ok, so I deleted the VMs, initialized a group of 2 4-core vms and then reran the as.cluster command, and I'm still running into the publickey issue.

`2019-03-11 17:51:50> External IP for instance vm1 : 35.197.66.179
Warning: Permanently added 'IP-Addy' (ED#) to the list of known hosts.
connor@Same-IP: Permission denied (publickey).`

**Comment by CMLennon** [comment]
Hi Mark,

I think I found a fix. The issue was resolved by re-downloading the JSON. My old JSON was valid, but for some reason was incorrectly reading the public key but only for certain operations (ie, I could create vms, ssh into them, but not assign tasks.) Thank you for your help and patience.

**Comment by MarkEdmondson1234** [comment]
Oh great news, I was puzzling about that one.  Thanks for letting us know.
