### ISSUE TITLE
Keras CPU template

### ISSUE THREAD

**Issue by GarryGelade** [cloudyr/googleComputeEngineR#134]
I would like to run Keras/Tensorflow in RStudio.  I haven't been able to install these packages into the RStudio or RStudio-persistent templates (I've been tearing my hair out trying to set up the right virtualenv for Python), so I was interested in the gpu template

Unfortunately I am using a free account and I don't want to pay for GPU access.

Would it be possible to produce a persistent template with Keras/Tensorflow pre-installed, but using CPU?  Thanks if you can assist.

**Comment by MarkEdmondson1234** [comment]
It’s possible as the Docker image for GPU from Rocker.org also includes a CPU only version. For that you won’t use the GPU template as that will launch a GPU so just use a standard RStudio template with a dynamic custom Docker image (see website) - IIRC the image name is rocker/tensorflow-cpu but check there.

**Comment by MarkEdmondson1234** [comment]
See here for the different Tensorflow/Keras images you can choose from https://github.com/rocker-org/ml

**Comment by GarryGelade** [comment]
Thanks for that idea Mark.

I managed to create a docker image (rocker/ml-gpu) in my repository, and I created an instance via:

```
vm <- gce_vm(template = "rstudio",
        name = "r-deep-learning",    # instance name
       username = "garry",
       password = "tensixtysix",
      predefined_type = "n1-highmem-2",
     dynamic_image = "gcr.io/rdeeplearning/rocker/ml-gpu") 
```



This gave me the following output:

 
```
==Google Compute Engine Instance==
 
Name:                r-deep-learning
Created:             2019-04-05 12:16:49
Machine Type:        n1-highmem-2
Status:              RUNNING
Zone:                europe-west2-c
External IP:         35.230.159.187
Disks: 
                 deviceName       type       mode boot autoDelete
1 r-deep-learning-boot-disk PERSISTENT READ_WRITE TRUE       TRUE
 
Metadata:  
                     key                              value
2               template                            rstudio
3 google-logging-enabled                               true
4           rstudio_user                              xxxxx
5             rstudio_pw                        xxxxxxxxxxx
6      gcer_docker_image gcr.io/rdeeplearning/rocker/ml-gpu
2019-04-05 20:17:13> Token exists.
2019-04-05 20:17:13> Request: https://www.googleapis.com/compute/v1/projects/rdeeplearning/global/firewalls/?
2019-04-05 20:17:13> http firewall exists: allow-http default-allow-http
2019-04-05 20:17:13> Token exists.
2019-04-05 20:17:13> Request: https://www.googleapis.com/compute/v1/projects/rdeeplearning/global/firewalls/allow-http/
2019-04-05 20:17:13> Token exists.
2019-04-05 20:17:13> Request: https://www.googleapis.com/compute/v1/projects/rdeeplearning/global/firewalls/default-allow-http/
2019-04-05 20:17:14> https firewall exists: allow-https
2019-04-05 20:17:14> Token exists.
2019-04-05 20:17:14> Request: https://www.googleapis.com/compute/v1/projects/rdeeplearning/global/firewalls/allow-https/
2019-04-05 20:17:14> r-deep-learning VM running
```
 

Which all looked great.  However, when I try to log in using the external IP/user name/password, I get a time out error.

Inspection of the instance showed HTTP traffic is allowed.

 

Any thoughts?

**Comment by MarkEdmondson1234** [comment]
Perhaps just wait, it can take a while to load first load.


________________________________

**Comment by GarryGelade** [comment]
That doesn’t seem to be the problem – I have waited about 20 minutes.

I can log in to VMs created using your standard rstudio image, so I guess my ports are open OK

 This is the output from docker ps if that’s any help

**Comment by MarkEdmondson1234** [comment]
If you are using `rocker/ml-gpu` then it is installing GPU drivers, you need the CPU based `rocker/ml`.  IT could be hanging if its expecting a GPU based VM.

**Comment by MarkEdmondson1234** [comment]
Or just launch a standard RStudio instance, and install via `install.packages("keras")` following the RStudio guide.  https://keras.rstudio.com/

**Comment by GarryGelade** [comment]
I have managed to create an image with keras installed on the docker hub, and I can successfully use it to launch an RStudio VM using:
```r
vm <- gce_vm(template = "rstudio",
             name = "r-deep-learning",    # projectId
             username = "rstudio",
             password = "XXX",
             predefined_type = "n1-highmem-2",
             dynamic_image = "registry.hub.docker.com/garrygelade/rocker-ml")
```
There is one thing I don't quite understand....
In the gce_vm command I have to use "rstudio" as the username, but when I use the external IP to sign in to my instance, I have to use the username "garry".

Can you explain this? I am not sure how the template and the image interact.  Otherwise, I am happy - thanks for your help!

**Comment by MarkEdmondson1234** [comment]
Great.  Actually I'm not sure how you can use "rstudio" as a  username as I put in code to disallow that, as its the username RStudio installs itself under.  You should use another name, what happens if you try that?

Perhaps the Docker container you have built included your username?

The template arguments determines which settings the Docker container is launched with.  "rstudio" opens up port 8787 and maps it to 80, etc.

**Comment by GarryGelade** [comment]
Sorry, you are quite right. I get an error if I use rstudio as a username in the gce_vm() function.

If I use a different username, the VM starts up.
