### ISSUE TITLE
Some packages fail to on RStudio Server

### ISSUE THREAD

**Issue by GarryGelade** [cloudyr/googleComputeEngineR#135]
The packages that won't install are
imager
magick
jpeg
Cairo
gmp (multiple precision arithmetic)
ClusterR (which has a dependency on gmp)

 sample error

trying URL 'https://cran.rstudio.com/src/contrib/gmp_0.5-13.5.tar.gz'
Content type 'application/x-gzip' length 133364 bytes (130 KB)

downloaded 130 KB

 Welcome to RStudio Server on Google Compute Engine! Today is Fri Apr  5 13:24:57 2019

* installing *source* package ‘gmp’ ...
** package ‘gmp’ successfully unpacked and MD5 sums checked
creating cache ./config.cache
checking for __gmpz_ui_sub in -lgmp... no
configure: error: GNU MP not found, or not 4.1.4 or up, see http://gmplib.org
ERROR: configuration failed for package ‘gmp’
* removing ‘/usr/local/lib/R/site-library/gmp’
Warning in install.packages :
  installation of package ‘gmp’ had non-zero exit status

**Comment by MarkEdmondson1234** [comment]
These packages need Linux dependencies that you can install first using the terminal via sudo apt-get. But long term I suggest you set it up with a custom Docker image with them installed, see website on launching RStudio with a custom environment
