### ISSUE TITLE
gce_list_instances() call fails with Unexpected TLS packet received

### ISSUE THREAD

**Issue by vsrdharca** [cloudyr/googleComputeEngineR#136]
@MarkEdmondson1234 

Hello Mark,

Intermittently over the last few days gce_list_instances() call fails. The instance is up and running but curl complains of an unexpected TLS packet received.

Any thoughts what might be causing this error? Seems authentication related. Is there a way to authenticate without creating a .Renviron?

Much thanks,

Sorry I didn't mean to tag this as a bug!

Below is the log:

> gce_list_instances()
Error in curl::curl_fetch_memory(url, handle = handle): gnutls_handshake() failed: An unexpected TLS packet was received.
Request failed [ERROR]. Retrying in 1 seconds...
Error in curl::curl_fetch_memory(url, handle = handle): gnutls_handshake() failed: An unexpected TLS packet was received.
Request failed [ERROR]. Retrying in 1 seconds...
Error in curl::curl_fetch_memory(url, handle = handle) : 
  gnutls_handshake() failed: An unexpected TLS packet was received.
2019-05-01 12:40:48> Request Status Code: 500
Error : is.response(x) is not TRUE
In addition: Warning message:
In retryRequest(do.call("RETRY", args = arg_list, envir = asNamespace("httr"))) :
  Request failed before finding status code. Retrying.
2019-05-01 12:40:48> Trying again: 1 of 5

Warning message:
No JSON content found in request

**Comment by MarkEdmondson1234** [comment]
Hello.  I'm afraid I've not come across this before, and I suspect it is not only `gce_list_instances()` that this would happen for as there is nothing particularly uinique about that function.  I guess it is a more general HTTP connection issue - it may be worth asking on the `curl` libraries GitHub issues.

Are you behind a proxy or have an unusual internet connection?

**Comment by vsrdharca** [comment]
@MarkEdmondson1234 
Thank you for your response. The error is when googleComputeEngineR authentication did not happen. Thanks again for your attention.
