### ISSUE TITLE
gce_vm_cluster fails to restart existing instances

### ISSUE THREAD

**Issue by grantmcdermott** [cloudyr/googleComputeEngineR#149]
**Describe the bug**

What it says on the tin: `gce_vm_cluster` fails if I feed it the names of previously instantiated instances, which have since been turned off.

**To Reproduce**
For the below reprex, I'll just build off the same example that I used in https://github.com/cloudyr/googleComputeEngineR/issues/148 (i.e. a cluster of two VMs with the implied names of "r-cluster-1/2").
``` r
library(googleComputeEngineR)
#> Setting scopes to https://www.googleapis.com/auth/cloud-platform
#> Successfully auto-authenticated via XXX.json
#> Set default project ID to 'XXX'
#> Set default zone to 'XXX'

vms <- 
  gce_vm_cluster(
    cluster_size = 2,               ## How many VMs in our cluster?
    predefined_type = "g1-small"    ## Cheap preemptible machine
    )
#> 2019-10-22 22:41:47> VM previously created but not running, starting VM
#> Error in if (operation$kind != "compute#operation") {: argument is of length zero
```

<sup>Created on 2019-10-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

FWIW, it might not be clear from the output, but the first VM in the cluster does get started. It's the others (2nd, 3rd, etc.) that fail to turn on. Again, in this regard it is similar to https://github.com/cloudyr/googleComputeEngineR/issues/148.

**Expected behavior**
To restart all VMs in the cluster, much the same as `gce_vm()` does for a single VM.

**Additional context**
Sorry to ping you with back-to-back issues. In my defense, I was only trying to add a nested parallel example to the docs, which I did promise you months ago.

**Comment by MarkEdmondson1234** [comment]
No worries, thanks for the issue.  I didn't cover this use case, which it should.

**Comment by MarkEdmondson1234** [comment]
Should be fixed now
