### ISSUE TITLE
WISH: Functions for setting up and returning an up-and-running instance 

### ISSUE THREAD

**Issue by HenrikBengtsson** [cloudyr/googleComputeEngineR#15]
When I was trying out the package, I found myself creating the following utility functions:

``` r
gce_vm <- function(name, ...) {
  tryCatch({
    vm <- gce_get_instance(name)
  }, error = function(ex) {
    vm <- gce_vm_template(name = name, ...)
  })
}

gce_vm_waitfor <- function(vm, max_tries = 100L, delta = 1.0) {
  ips <- gce_get_external_ip(vm)
  if (is.null(ips)) {
    gce_vm_start(vm)
    for (kk in seq_len(max_tries)) {
      vm <- gce_get_instance(vm$name)
      ips <- gce_get_external_ip(vm)
      if (!is.null(ips)) break
      Sys.sleep(delta)
    }
  }
  invisible(vm)
}
```

These would allow me to do:

``` r
if (!exists("vm")) {
  vm <- gce_vm(name = "r-demo", template = "r-base", predefined_type = "f1-micro")
  vm <- gce_vm_waitfor(vm)
  ## gce_ssh_setup(instance = vm, ...)
}
print(vm)


library("future")
cl <- as.cluster(vm)
plan(cluster, workers = cl)
x %<-% { Sys.info() }
print(x)
```

so that if the instance was already running and I reran my script, it would pick up the running instance.  If not running, it would launch one and wait for it to be fully up and running.

I can imagine this is a common use pattern; does function for this already exists in the package, or would it make sense to add something like this to the API?

**Comment by MarkEdmondson1234** [comment]
First thanks very much for the issues/forks, it is most welcome.  I'm mainly getting it working for my use cases at work so another opinion is needed.

There isn't an equivalent of your `gce_vm` but that can be arranged, I can see the utility of it.

There is an existing function for your `gce_vm_waitfor`.  When you use `gce_vm_create` or its derivatives, or long running tasks like creating disks, it returns immediately not with a VM object but an [operation object](https://cloud.google.com/compute/docs/reference/latest/zoneOperations) which you can query by passing its name to see if the task is complete yet. It is called `gce_check_zone_operation` but I just added an alias of `gce_wait` as its easier to remember :)  It lets you specify a wait time in-between checks. 

The `gce_vm_template` function includes this function within it, so you always wait with that.

I was thinking of use the same function to wait for R functions that are running with the futures package.

**Comment by HenrikBengtsson** [comment]
Great, found [`gce_check_zone_op()` and new `gce_wait()`](https://github.com/cloudyr/googleComputeEngineR/blob/fc8cfd09f6c99016a1575861b3bbba16c110720c/R/operations.R#L122-L194).  I didn't know `gce_vm_template()` did this internally - so mostly only useful when launching manually online.

About:

> I was thinking of use the same function to wait for R functions that are running with the futures package.

I'm not sure what you're after here.  By definition / design, the call will block until a future is resolved when one tries to retrieve its value.  It's possible to check whether a future has been resolved or not without blocking by using `resolved()`.  I don't there's anything you need to do in googleComputeEngineR; the future package should take care of it automatically.

**Comment by MarkEdmondson1234** [comment]
Yes, it was using `resolved()` I thought about using - so any asynchronous action such as starting a VM or running a function on a VM with future has a generic `gce_check` that you can see if its done.

**Comment by MarkEdmondson1234** [comment]
I just added `gce_vm` based on your tryCatch above, but added some conditions for the different styles of creation such as non-template or non-docker instances.

**Comment by MarkEdmondson1234** [comment]
This is now well covered in `gce_vm` which will look for an instance of the same name that may be stopped and start it, or get an existing running instance, or start up a VM with template or docker containers as needed. 

``` r
gce_vm <- function(name, 
                   ...,                           
                   project = gce_get_global_project(), 
                   zone = gce_get_global_zone() ) {

  stopped <- gce_list_instances("status eq TERMINATED", project = project, zone = zone)

  if(name %in% stopped$items$name){
    myMessage("VM previously created but not running, starting VM", level = 3)
    job <- gce_vm_start(name, project = project, zone = zone)
    gce_wait(job)
  }

  vm <- tryCatch({
    suppressMessages(suppressWarnings(gce_get_instance(name)))
  }, error = function(ex) {
    dots <- list(...)
    if(!is.null(dots[["template"]])){

      myMessage("Creating template VM", level = 3)
      do.call(gce_vm_template, c(list(...), name = name))
      ## gce_vm_template has its own gce_wait()

    } else if(any(!is.null(dots[["file"]]), !is.null(dots[["cloud_init"]]))){

      myMessage("Creating container VM", level = 3)
      job <- do.call(gce_vm_container, c(list(...), name = name))
      gce_wait(job)
      gce_get_instance(name)

    } else {

      myMessage("Creating standard VM", level = 3)
      job <- do.call(gce_vm_create, c(list(...), name = name))
      gce_wait(job)
      gce_get_instance(name)

    }
  })

  myMessage("VM running", level = 3)
  vm
}
```
