### ISSUE TITLE
Error: API returned: Insufficient Permission: Request had insufficient authentication scopes.

### ISSUE THREAD

**Issue by alex-datalabs** [cloudyr/googleComputeEngineR#155]
**Describe the bug**
I cannot run gce_vm() to create vm with template due to error:

```
Request Status Code: 403
Error: API returned: Insufficient Permission: Request had insufficient authentication scopes.
```

**To Reproduce**
```
Sys.setenv("GCE_AUTH_FILE" = "C:/Users/axel/Documents/python-for-bigquery.json")
library(googleComputeEngineR)

gce_global_project("python-for-bigquery")
gce_global_zone("us-central1-a")


vm <- gce_vm(template = "rstudio-hadleyverse",
             name = "rstudio-team",
             username = "mark", password = "mark1234",
             predefined_type = "n1-highmem-2")
```

**Expected behavior**
I want to create Templated Container based VM

**Session Info**
```
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Russian_Russia.1251  LC_CTYPE=Russian_Russia.1251    LC_MONETARY=Russian_Russia.1251 LC_NUMERIC=C                   
[5] LC_TIME=Russian_Russia.1251    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.12.8          googleAuthR_1.1.1          bigrquery_1.2.0            searchConsoleR_0.4.0       googleComputeEngineR_0.3.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3       rstudioapi_0.10  bit_1.1-14       R6_2.4.1         rlang_0.4.2      httr_1.4.1       globals_0.12.5  
 [8] tools_3.5.2      parallel_3.5.2   DBI_1.1.0        askpass_1.1      openssl_1.4.1    yaml_2.2.0       bit64_0.9-7     
[15] assertthat_0.2.1 digest_0.6.23    tibble_2.1.3     gargle_0.4.0     crayon_1.3.4     fs_1.3.1         codetools_0.2-16
[22] curl_4.3         memoise_1.1.0    glue_1.3.1       compiler_3.5.2   pillar_1.4.2     jsonlite_1.6     future_1.15.1   
[29] listenv_0.8.0    pkgconfig_2.0.3 

```

**Comment by MarkEdmondson1234** [comment]
The name of your json file suggests it has only got BigQuery scopes assigned to it in the GCP console, which would explain the error.  Assign Compute Engine Admin scopes to the same service key, or create a new one with those scopes.

**Comment by alex-datalabs** [comment]
Hi Mark. No, I assigned the right roles. It's just the name of the file for me. Here is the screenshot of roles:
![image](https://user-images.githubusercontent.com/60977575/74426125-7d56ff80-4e5d-11ea-8b11-ff41c391aabc.png)

**Comment by MarkEdmondson1234** [comment]
That looks like it should work - I'm sorry I can't really tell any more from the info we have, I would try making a new service account on GCP and using that for auth instead.  You could also try running with `options(googleAuthR.verbose=2)` to generate more R logs, but it looks like its a GCP IAM issue.

**Comment by alex-datalabs** [comment]
Ok, thanks, I understand. What kind of roles should be assigned more? As I understand, Compute Admin is maximum for VM. Also, is it possible to assign scopes other way maybe? Documentation is not clear about it for R. To be clear - can I get from the package what particular scope I am lacking?

**Comment by MarkEdmondson1234** [comment]
Editor role is usually more than sufficient, which is what is confusing about it. It makes me think that auth is not being used somehow.  Compute Admin should also be sufficient. 

Oh what it could be is that the scopes are not set - could you see what `getOption("googleAuthR.scopes.selected")` returns?  It should be "https://www.googleapis.com/auth/cloud-platform"

**Comment by alex-datalabs** [comment]
Yep, you were right. getOption() returned 'NULL'. What is the best way to fix it?

**Comment by MarkEdmondson1234** [comment]
Ok cool, thats it then.  It should be set on package load, so thats odd still, but if you set it and then reload the library it should work

`options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/cloud-platform")`

**Comment by alex-datalabs** [comment]
Unfortunately, it did not help. Scope is set but the error 403 is still there. Can the version of R itself affect that?

**Comment by MarkEdmondson1234** [comment]
Order matters, since the scope needs to be set before authentication - can you try below:

```r
#RESTART R THEN
options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/cloud-platform")
Sys.setenv("GCE_AUTH_FILE" = "C:/Users/axel/Documents/python-for-bigquery.json") #<- better in .Renviron
library(googleComputeEngineR)
# auto auth message should appear here

do_auth_stuff
```

**Comment by alex-datalabs** [comment]
Yes, the order was the problem and restart. Thanks a lot!

**Comment by abalter** [comment]
[This](https://github.com/r-lib/gargle/issues/138#issuecomment-1114133838) also helped me.
