### ISSUE TITLE
Using with R v<4.0

### ISSUE THREAD

**Issue by mcombs33** [cloudyr/googleComputeEngineR#160]
Hello,

Is it possible to start an RStudio session using a previous version of the R software? My VM now uses R 4.0 by default, but many packages are not yet compatible with the newest R and some older packages may never be updated. Is there a way to change the default version of R to something <v4.0? Thanks for your help!

**Comment by MarkEdmondson1234** [comment]
Yes you can call using an older version of the rocker images, I don't know your exact command but for instance rocker/rstudio:3.6.3 would be launched via:

```r
gce_vm(name = "rstudio-363",
       template = "rstudio",
       dynamic_image = "rocker/rstudio:3.6.3",
       username = "me", password = "mypassword")
```

See the section on "custom rstudio server" on the website: https://cloudyr.github.io/googleComputeEngineR/articles/rstudio-team.html#start-up-another-vm-your-configuration

**Comment by mcombs33** [comment]
Thank you! This is exactly what I was looking for.
