### ISSUE TITLE
Cannot stop vm

### ISSUE THREAD

**Issue by sstoeckl** [cloudyr/googleComputeEngineR#162]
**Describe the bug**
I am running the initial example from the documentation:
`library("googleComputeEngineR")`
`vm <- gce_vm(template = "rstudio",
             name = "rstudio-test",
             username = "rstudio", password = "jgher84rhf84zhfnb457utrfhjn3e4f",
             predefined_type = "n1-highmem-2")`
which works well (I can log into rstudio-server) but whenever I try to stop the instance using
`gce_vm_stop(vm)`
I get the error message:

> 2020-05-27 12:00:01> Request Status Code: 400
> Fehler: API returned: Invalid value for field 'instance': '2020-05-27T02:12:55.076-07:00'. Must be a match of regex '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?|[1-9][0-9]{0,19}'

Not being able to stop a vm seems like a rather severe bug.

**Session Info

> R version 3.6.3 (2020-02-29)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 17763)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                    LC_TIME=German_Germany.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] googleComputeEngineR_0.3.0.9000 devtools_2.2.2                  usethis_1.5.1                  
> 
> loaded via a namespace (and not attached):
>  [1] compiler_3.6.3    googleAuthR_1.2.1 prettyunits_1.1.1 remotes_2.1.1     tools_3.6.3       testthat_2.3.2    digest_0.6.25     packrat_0.5.0    
>  [9] pkgbuild_1.0.8    pkgload_1.0.2     jsonlite_1.6.1    memoise_1.1.0     gargle_0.5.0      rlang_0.4.6       cli_2.0.2         rstudioapi_0.11  
> [17] curl_4.3          parallel_3.6.3    withr_2.2.0       httr_1.4.1        desc_1.2.0        fs_1.4.1          askpass_1.1       globals_0.12.5   
> [25] rprojroot_1.3-2   glue_1.4.1        listenv_0.8.0     R6_2.4.1          processx_3.4.2    fansi_0.4.1       sessioninfo_1.1.1 callr_3.4.3      
> [33] magrittr_1.5      backports_1.1.7   ps_1.3.3          codetools_0.2-16  ellipsis_0.3.1    assertthat_0.2.1  future_1.17.0     openssl_1.4.1    
> [41] crayon_1.3.4

**Comment by MarkEdmondson1234** [comment]
I think if you use `gce_vm_stop("rstudio-test")` it will work, I will look at why VM objects aren't being recognised.

**Comment by sstoeckl** [comment]
That worked for me, thanks Mark!
