### ISSUE TITLE
r-parallel.yaml name error

### ISSUE THREAD

**Issue by burgikukac** [cloudyr/googleComputeEngineR#165]
**Describe the bug**
The r-parallel.yaml file has wrong extension: yml - so system.file won't find it.

**Comment by burgikukac** [comment]
see PR #166, even dynamic.yml had the wrong extension

**Comment by MarkEdmondson1234** [comment]
Thanks!  Yes this is an annoying bug, RStudio makes the file name one way, but some only support 3-letter extensions.  I am trying to be consistent in another package with yml but yaml should still be expected.  A test to catch it is also a good idea.
