### ISSUE TITLE
Rstudio server on google cloud

### ISSUE THREAD

**Issue by stevenlehrer** [cloudyr/googleComputeEngineR#169]
I am able to log in to google cloud with filezilla. Does anyone know in which directory the data files and script files for Rstudio server are stored?

**Comment by MarkEdmondson1234** [comment]
Are you logging into its VM or the Docker container?  Does anything on the website help?
https://cloudyr.github.io/googleComputeEngineR/articles/troubleshooting.html

**Comment by stevenlehrer** [comment]
I am trying to copy a file from a bucket to Rstudio server. I was able to log in with filezilla and got the path. The syntax below gets the entire file copied but not put where I can find it.

gsutil cp gs://church/ukb53365.tab rstudio.cloud/peaceful-web-388023//home/pamela/r

Do you know what is wrong with my syntax?

________________________________

**Comment by MarkEdmondson1234** [comment]
If this is for RStudio running at  https://rstudio.cloud then its not covered by this repo, you should ask on RStudio's forums https://community.rstudio.com/c/rstudio-cloud/14
