### ISSUE TITLE
Suspend an Instance

### ISSUE THREAD

**Issue by muschellij2** [cloudyr/googleComputeEngineR#172]
**Is your feature request related to a problem? Please describe.**
Be able to suspend, not stop, an instance. 

**Describe the solution you'd like**
Similar to gce_vm_suspend.

**Describe alternatives you've considered**
Adding a PR in a minute.

**Additional context**
Suspend is only supported in beta, so I'm not sure about how much you are supporting of that: https://cloud.google.com/compute/docs/reference/rest/beta/instances/suspend

**Comment by MarkEdmondson1234** [comment]
Nice, I didn't know about this feature - this will be very useful for those wishing to persist data between sessions.  I will take a look but initial review looks great.  I would like to run the test at least once locally to see it in action.

**Comment by muschellij2** [comment]
Let me add the `resume` endpoint as well (otherwise it's not that helpful to just suspend!)
