### ISSUE TITLE
R runtime support cloud functions

### ISSUE THREAD

**Issue by muschellij2** [cloudyr/googleComputeEngineR#175]
You can close this immediately, I just figured it'd be nice if an R runtime was supported by Cloud Function to make scheduled scripts much easier, so if you can link to the issue and see if people will star it, may get some visibility: https://issuetracker.google.com/issues/151561571

**Comment by MarkEdmondson1234** [comment]
This is pretty much what googleCloudRunner was made for - CloudRun has many Cloud Function like features https://code.markedmondson.me/googleCloudRunner/articles/cloudrun.html - its not quite the same, put even Python workloads may prefer Cloud Run for some use cases even when supported directly in Cloud function.

**Comment by muschellij2** [comment]
Agreed.  googleCloudRunner is the best solution we've found for submitting jobs (even Python ones).  I'm all for using it, but I was just trying to get r community to show Google it would like integration in GCP

**Comment by MarkEdmondson1234** [comment]
Makes sense!  R is available within Colab and some other notebook offerings. I doubt they will include it outside of direct data science applications though such as Cloud Functions but worth seeing if the demand is there.

**Comment by MarkEdmondson1234** [comment]
@muschellij2 did you get my email reply?  Just checking on a known non-spam folder channel :)
