### ISSUE TITLE
Persistent Studio Github VM launching but timing out 

### ISSUE THREAD

**Issue by mzusev** [cloudyr/googleComputeEngineR#176]
**Describe the bug**
I am following the example from this page of the documentation: [Persistent Rstudio Github](https://cloudyr.github.io/googleComputeEngineR/articles/persistent-rstudio.html#github). The VM appears to launch as normal, but when I click on the external IP, the message is the site can't be reached, the address took too long to respond. I have tried several times, waiting up to 40 minutes for the image to install, but no luck. 

**To Reproduce**
Follow the example shown in the documentation. 

```
vm <- gce_vm(name="cloud-rstudio-demo", 
             predefined_type = "n1-standard-1", 
             template = "rstudio", 
             username = "michael", password = "demo", 
             dynamic_image = "gcr.io/gcer-public/persistent-rstudio")
```

**Expected behavior**
A persistent R Studio image. 

**Screenshots**
CPU Usage when creating vm. 
![2021-07-06 14_20_20-Window](https://user-images.githubusercontent.com/73913543/124648580-6efbf000-de65-11eb-97f7-f786ae67c21e.png)

docker ps
![2021-07-06 14_21_59-Window](https://user-images.githubusercontent.com/73913543/124648711-96eb5380-de65-11eb-97a7-5d719b07d4bb.png)

**Session Info
Please run `sessionInfo()` and put results here:

```
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252 LC_NUMERIC=C                   
[5] LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] googleComputeEngineR_0.3.0

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13   parallelly_1.26.1 magrittr_2.0.1    usethis_2.0.1     R6_2.5.0          rlang_0.4.11      fastmap_1.1.0     httr_1.4.2       
 [9] globals_0.14.0    tools_4.1.0       parallel_4.1.0    cli_2.5.0         googleAuthR_1.4.0 askpass_1.1       openssl_1.4.4     assertthat_0.2.1 
[17] digest_0.6.27     gargle_1.2.0      lifecycle_1.0.0   purrr_0.3.4       fs_1.5.0          codetools_0.2-18  curl_4.3.1        memoise_2.0.0    
[25] glue_1.4.2        cachem_1.0.5      compiler_4.1.0    jsonlite_1.7.2    future_1.21.0     renv_0.13.2       listenv_0.8.0 
```

**Additional context**
There are instructions in [gce_vm_template documentation](https://cloudyr.github.io/googleComputeEngineR/reference/gce_vm_template.html) to use docker_run on dynamic images.Even though it is not part of the example, I tried the following with an error message: 

`docker_run(host = vm, image = "gcr.io/gcer-public/persistent-rstudio", user="michael")`

Error: 

`Error in gce_ssh_addkeys(instance, key.pub = key.pub, key.private = key.private,  : 
  No SSH public/private key given and no google_compute_engine.pub not found.FALSE`

Thanks in advanced!

**Comment by MarkEdmondson1234** [comment]
Thanks, strange bug. I think the firewall is not being opened correctly. Do you see the same issues with other templates?

**Comment by mzusev** [comment]
No other issue with other templates: 

```
vm <- gce_vm("cloud-rstudio-demo-test", 
             predefined_type = "n1-standard-1", 
             template = "rstudio", 
             username = "michael", password = "demo")
```
This works as expected. 

Any ideas on how to open the firewall correctly?

**Comment by mzusev** [comment]
A colleague found this in the logs: 

`"Not continuing with pull after error: error pulling image configuration: error parsing HTTP 400 response body: invalid character '<' looking for beginning of value: \"<?xml version='1.0' encoding='UTF-8'?><Error><Code>UserProjectMissing</Code><Message>Bucket is a requester pays bucket but no user project provided.</Message><Details>Bucket is Requester Pays bucket but no billing project id provided for non-owner.</Details></Error>\""`

**Comment by MarkEdmondson1234** [comment]
Ah ok, that makes sense as I just changed that due to rising costs.  But I will change it back for now until I can figure out how to handle it.  Try it again in 5 mins.

**Comment by mzusev** [comment]
That worked. Thank you!
