### ISSUE TITLE
Is `dynamic_image` required in `gce_vm()`?

### ISSUE THREAD

**Issue by jennybc** [cloudyr/googleComputeEngineR#181]
I got this error when I ran code copied from the docs:

``` r
vm <- gce_vm(
  template = "rstudio",
  name = "gargle-gce-rstudio-server",
  username = "jenny", password = "1234"
)
#> 2021-11-04 15:03:44> Creating template VM
#> Error in if (grepl("^http(s|)://gcr.io/", dynamic_image)) { : 
#>   argument is of length zero
```

which is what happens when we hit

https://github.com/cloudyr/googleComputeEngineR/blob/b5b52ca8587ed9d9c02237faa0b081bd38c5d96b/R/template.R#L109

with `dynamic_image = NULL`, which is the default.

I got unstuck with #182.

**Comment by MarkEdmondson1234** [comment]
Ah thank you, this must be GitHub version as it got introduced in https://github.com/cloudyr/googleComputeEngineR/pull/173 recently.  thanks for the fix.  (cc @muschellij2 who needed the original code to fix #172)
