### ISSUE TITLE
DOCS: Project name vs Project ID 

### ISSUE THREAD

**Issue by HenrikBengtsson** [cloudyr/googleComputeEngineR#21]
So, I'm fairly new to GCP, so forgive if this is a FAQ, but I just created a new GCP project named 'research-2016'.   This resulted in:

* Project name: `research-2016`
* Project ID: `research-2016-149512`
* Project number: `627573128191`

Given the above, it is not immediately clear from the [docs](https://cloudyr.github.io/googleComputeEngineR/articles/installation-and-authentication.html) what `GCE_DEFAULT_PROJECT` should be, but from trial and error I learned at it should be the **Project ID**.  For the longest I tried with the Project name, but got stuck with errors basically such as:
```r
> d <- gce_get_project()
Request Status Code: 403
Error in checkGoogleAPIError(req) : 
  JSON fetch error: Access Not Configured. Compute Engine API has not been used in project 578809911671 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute_component/overview?project=578809911671 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```
Using the **Project ID** things work as expected.  May I suggest to rename `GCE_DEFAULT_PROJECT` to `GCE_DEFAULT_PROJECT_ID` to make this non-ambiguous?

Also, when I have the above set up, I get:
```r
> library(googleComputeEngineR)
Setting scopes to https://www.googleapis.com/auth/cloud-platform
If you need additional scopes set do so via options(googleAuthR.scopes.selected = c('scope1', 'scope2')) before loading library and include one required scope.
Successfully authenticated via ~/.ssh/GoogleComputeEngine/research-2016-00a0b75271f4.json
Set default project name to 'research-2016-149512'
Set default zone to 'us-west1-a'
```
Note how the message mention **project name**; should it say **project ID** instead?

PS. I didn't notice this in my previous test setup, because there the project name and the project ID were identical.

**Comment by MarkEdmondson1234** [comment]
To be honest this is news to me too, I thought project-number and project-id both worked, at least for my projects they have been interchangeable.  Maybe they change if numbers are involved.  I will do some reading and update as you suggest.

**Comment by MarkEdmondson1234** [comment]
Ok seems you can have them all different.  I'll add a screenshot like from here to make it clearer
https://updraftplus.com/faqs/where-do-i-find-my-google-project-id
