### ISSUE TITLE
Add firewall rule function

### ISSUE THREAD

**Issue by terzieff** [cloudyr/googleComputeEngineR#34]
I finally managed to test the library from Mac and get RServer running today, but before that I stumbled upon the firewall problem. GCE doesn't allow http access by default, so I had to add this manually, but I thought it could be included in the package as to make the whole "2 lines of R, get the IP and log-in" concept more real ; )

I wrote the function below:

```
gce_add_firewall_rule <- function(name,
                                  protocol,
                                  ports,
                                  sourceRanges,
                                  project = gce_get_global_project()) {
  url <-
    sprintf("https://www.googleapis.com/compute/v1/projects/%s/global/firewalls",
            project)
  
  the_rule <- jsonlite::toJSON(list(
    name = name,
    allowed = list(list(IPProtocol = protocol, ports = list(ports))),
    sourceRanges = I(sourceRanges)),
    auto_unbox = T
  )
  
  f <- gar_api_generator(
    url,
    "POST",
    customConfig = list(
      httr::add_headers("Content-type" = "application/json")
    ))

  out <- f(the_body = the_rule)
 
}
```

It seems to do the job with basic scenario: `gce_add_firewall_rule("allow-http", "tcp", "80", "0.0.0.0/0")`. It doesn't work with multiple ports, but this json stuff is killing me, so I'll have to give up for now.

**Comment by MarkEdmondson1234** [comment]
Good point, I think I may have added the http ports to the default network a long time ago so forgot it's a setup step. I also think if the instance is tagged http it should work also, will check why that's not the case.

**Comment by MarkEdmondson1234** [comment]
@terzieff hmm the instance should have been created with the "http-server" tag that opens the port for you - does your project not have that tag in its networks? (Check via web UI)

**Comment by MarkEdmondson1234** [comment]
It looks like they changed firewalls recently https://cloud.google.com/compute/docs/networking#addingafirewall

**Comment by terzieff** [comment]
@MarkEdmondson1234 Yup, the "http-server" tag is there, but as you probably know by now, it doesn't do much so they must have changed something. I also noticed the section below in the instance options - but it seems inactive (and there's no word about it in the documentation).
![image](https://cloud.githubusercontent.com/assets/11526532/21639865/aaff9f2e-d272-11e6-8f83-db9562cc4371.png)

**Comment by MarkEdmondson1234** [comment]
@terzieff Ok cool, thanks Google :)  I will add a line to open the ports for that tag then, which will mean adding the API call.  For now you can do it via the Web UI (right?)

**Comment by MarkEdmondson1234** [comment]
New networks no longer have a http/https connection, must set it up: https://cloud.google.com/compute/docs/networking#gcloud-compute-external-http

**Comment by MarkEdmondson1234** [comment]
@terzieff this should be fixed now.  `gce_vm` now has a default argument that will open the 80 or 443 ports if necessary.  General firewall functions are available too here: https://github.com/cloudyr/googleComputeEngineR/blob/master/R/firewalls.R
