### ISSUE TITLE
Not able to use a custom disk_source in `gce_vm_create`

### ISSUE THREAD

**Issue by jburos** [cloudyr/googleComputeEngineR#36]
I'm trying to launch a gcloud VM with a larger boot disk, so that I can build my images without running out of disk space. 

So my naive first attempt was to create a boot disk from the source image & pass that option to `gce_vm_create`: 

```r
boot_disk <- gce_make_boot_disk(
  diskType = 'PERSISTENT',
  sourceImage = 'https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-8',
  diskSizeGb = 30,
  diskName = 'boot')

build_vm <- gce_vm_create('my-build-image', disk_source = boot_disk)

```

Here is the output:
```sh
> boot_disk <- gce_make_boot_disk(diskType = 'PERSISTENT', sourceImage = 'https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-8', diskSizeGb = 30, diskName = 'boot')
> build_vm <- gce_vm_create('my-build-image', disk_source = boot_disk)
Error in gce_vm_create("my-build-image", disk_source = boot_disk) : 
  Can specify only one of 'image_project' or 'disk_source' arguments.
```

I then tried various ways of nullifying the 'image_project' parameter, none of which were successful:

```r
> build_vm <- gce_vm_create('my-build-image', disk_source = boot_disk, image_project = NA)
Error in if (nchar(image_project) > 0) { : 
  missing value where TRUE/FALSE needed
> build_vm <- gce_vm_create('my-build-image', disk_source = boot_disk, image_project = '')
Error in gce_vm_create("my-build-image", disk_source = boot_disk, image_project = "") : 
  Need to specify either an image_project or a disk_source
```

Finally, I thought maybe I could resize the boot disk after VM creation: 

```r
build_vm <- gce_vm(name = vm_name, 
                     template = template, 
                     predefined_type = 'n1-standard-2')
  
build_vm_disk <- gce_get_disk(disk = vm_name)
## resize disk 
```

But then I saw that the function (`disks.resize`) implementing the [compute.disks.resize](https://cloud.google.com/compute/docs/reference/latest/disks/resize) API method was commented-out in [R/disks.R](https://github.com/cloudyr/googleComputeEngineR/blob/1b890d22be724ad4af083a59593befbd3638f0f5/R/disks.R#L465). 

Please let me know if I am missing something - and/or if there is another way to pass the disk_source to `gce_vm_create`. Again thanks for the great packages!

**Comment by MarkEdmondson1234** [comment]
Its supposed to work you just need as you specified here:  `build_vm <- gce_vm_create('my-build-image', disk_source = boot_disk, image_project = '')` or `build_vm <- gce_vm_create('my-build-image', disk_source = boot_disk, image_project = NULL)` but that syntax could be improved.

...but maybe the logic needs looking at here ( https://github.com/cloudyr/googleComputeEngineR/blob/master/R/vms.R#L197 ).  

This is the offending block, that I will take a look at:

```r
  ## if an image project is defined, create a source_image_url
  if(nchar(image_project) > 0){
    if(!is.null(disk_source)){
      stop("Can specify only one of 'image_project' or 'disk_source' arguments.")
    }

    if(nchar(image_family) > 0){
      
      ## creation from image_family
      source_image_url <- gce_make_image_source_url(image_project, family = image_family)
    } else {
      ## creation from image
      stopifnot(nchar(image) > 0)
      source_image_url <- gce_make_image_source_url(image_project, image = image)
    }
    
    if(is.null(source_image_url)){
      stop("No source image URL was found for selected image")
    }
    
  } else {
    source_image_url <- NULL
    if(!is.null(disk_source)){
      stop("Need to specify either an image_project or a disk_source")
    }
  }
```

**Comment by jburos** [comment]
Agreed. It does seem like there are two parts to this - one is treating image_project = '' and image_project = NULL the same. The second is correctly handling the disk_source. 

I took a pass at these -- see commit 1c23d75 -- and it now appears that I am creating the boot disk incorrectly. 

Here's what I see after making those changes: 

```r
> boot_disk <- gce_make_boot_disk(
+     diskType = 'PERSISTENT',
+     sourceImage = 'https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-8',
+     diskSizeGb = 30,
+     diskName = 'boot')
> 
> build_vm <- gce_vm_create('my-build-image', disk_source = boot_disk, image_project = NULL)
Request Status Code: 400
 Show Traceback
 
 Rerun with Debug
 Error in checkGoogleAPIError(req) : 
  JSON fetch error: Invalid value for field 'resource.disks[0]': ''. Boot disk must have a source specified. 
```

Which I thought at first was promising, but then I realized that the `else` logic above sets source_image_url to NULL and then constructs the init_disk .. I think my understanding of what to pass in as `disk_source` isn't quite correct since I was constructing that boot disk object & in fact the init_disk is constructed later within this function.

Anyways. Not sure the right way to solve this but posting these notes here in case it's helpful ..
