### ISSUE TITLE
feature request to change size of boot disk on gce_vm_create

### ISSUE THREAD

**Issue by jburos** [cloudyr/googleComputeEngineR#38]
Related to issue #36, seems like an easier route to achieve that goal would be to add a parameter for the diskSizeGb in the gce_vm_create function. 

I have a test implementation of this [in a branch](https://github.com/jburos/googleComputeEngineR/tree/add-disk-size-param) that is working in my limited tests.

Currently implemented as: 

```r
# optional parameter 
build_vm <- gce_vm_create('my-build-image3', disk_size_gb = 20)
build_vm <- gce_vm_create('my-build-image4')
```
 
This seems like a much cleaner way to increase the size of the boot disk, rather than create the disk separate from the vm & pass in a reference.

**Comment by MarkEdmondson1234** [comment]
Great, I'm on mobile now but will look to merge and pull a test tomorrow. I'm trying to keep ahead on unit tests so will add one at the same time. Thanks ever so much for the contribution!

**Comment by jburos** [comment]
Thanks. I just added one test case; hopefully this will run on travis when I do the PR.

**Comment by MarkEdmondson1234** [comment]
Thanks so much, its all checked out.  I added you to the contributor list.
