### ISSUE TITLE
Java not included

### ISSUE THREAD

**Issue by lrkirven** [cloudyr/googleComputeEngineR#49]
This is not a bug, but just a question. I need java included on my 'googleComputeEngineR' Compute Engine instance which I need to include rJava. What is the recommended way to do this?  When I try to manually load java, the /usr filesystem is real-only and it doesn't seem like I can add /usr/bin/java, which rJava is requiring. I appreciate any help or advice that you can provide.

**Comment by MarkEdmondson1234** [comment]
You can create your own Docker image which installs Java and rJava for you, then use that to launch your VM.  Check out some of the examples on the website and in the /inst folder.

**Comment by lrkirven** [comment]
Thanks!

**Comment by lrkirven** [comment]
Thanks!
