### ISSUE TITLE
containerit - Automatic generation of Dockerfiles of your R environment, oh my!

### ISSUE THREAD

**Issue by MarkEdmondson1234** [cloudyr/googleComputeEngineR#54]
This promises some automation heaven
http://o2r.info/2017/05/30/containerit-package/

1. Make your R code
2. Run https://github.com/o2r-project/containerit to generate a Dockerfile with your system depedecies
3. Use `docker_build` or build triggers to create image on Google container registry
4. Launch VM using `dynamic_image`

This is quite exciting.  Also works with Rmd and Shiny files.

Related issues 
https://github.com/cloudyr/googleComputeEngineR/issues/41
https://cloudyr.github.io/googleComputeEngineR/articles/single-scheduler.html

**Comment by nuest** [comment]
Glad you're interested! Let me know if you have any issues with `containerit`! It's really a first beta, so I look forward to bugs and questions.

**Comment by MarkEdmondson1234** [comment]
Thanks @nuest !  I notice you also depend on `harbor`, for CRAN I pulled in the functions into this one but hopefully `harbor` will hit CRAN soon (see https://github.com/wch/harbor/issues/5)

But for now, perhaps the functions pulled in will be useable by `containerit` ?  I may want to write some wrapper functions for users, although just updating the documentation with a workflow using `containerit` will be my aim now.

**Comment by MarkEdmondson1234** [comment]
Another useful package could be https://github.com/ColinFay/dockerfiler which will let changes to the generated Dockerfile be applied.
