### ISSUE TITLE
Question: GCP preemptible VMs

### ISSUE THREAD

**Issue by mgahan** [cloudyr/googleComputeEngineR#55]
This is an awesome package! Really appreciate all the work you have put into this. I was just curious - is it possible to use the current package to create preemptible-VMs?

Thanks so much,
Mike

**Comment by MarkEdmondson1234** [comment]
Yep you can do this via the scheduling argument:

```r
scheduling = list(preemptible = TRUE)
```

You will need to sort out how to save state if that happens in a shutdown script etc. However, these are much cheaper.  I'll add some documentation to the `gce_vm_create` function

```r
vm <- gce_vm("prempt1", scheduling =  list(preemptible = TRUE))
```

**Comment by mgahan** [comment]
Awesome! Thanks for the quick response
