### ISSUE TITLE
Question: Massively parallel processing

### ISSUE THREAD

**Issue by mgahan** [cloudyr/googleComputeEngineR#56]
So I am going through the **Massively parallel processing** tutorial, which is awesome and could really help me with my workflows. However, I keep getting an error when I use the `plan` function.

```
> plan(cluster, workers = fiftyvms)
Error: check_ssh_set(x) is not TRUE
```

Any idea on how to avoid this error? I am able to ssh into each of the instances using the `gce_ssh` function, so I think everything is fine with my ssh keys, but I could be missing something.

Thanks,
Mike

```
# Libraries
library(googleComputeEngineR)
library(future)

## auto auth to GCE via environment file arguments

## create 50 preemptible CPUs as they are much cheaper
vm_names <- paste0("cpu",1:3)

## specify the cheapest VMs that may get turned off
preemptible = list(preemptible = TRUE)

## start up 50 VMs with R base on them (can customise via Dockerfiles)
fiftyvms <- lapply(vm_names, gce_vm, predefined_type = "n1-standard-1", template = "r-base", scheduling = preemptible)

# Check ssh on each of machines
> gce_ssh(fiftyvms[[1]], "echo foo")
2017-06-11 11:07:17> Public SSH key uploaded to instance
Warning: Permanently added 'XX.XXX.XXX.XXX' (RSA) to the list of known hosts.
foo
[1] TRUE
> gce_ssh(fiftyvms[[2]], "echo foo")
2017-06-11 11:07:26> Public SSH key uploaded to instance
Warning: Permanently added 'XX.XXX.XXX.XXX' (RSA) to the list of known hosts.
foo
[1] TRUE
> gce_ssh(fiftyvms[[3]], "echo foo")
2017-06-11 11:07:37> Public SSH key uploaded to instance
Warning: Permanently added 'XX.XXX.XXX.XXX' (RSA) to the list of known hosts.
foo
[1] TRUE

## once all launched, add to cluster
exists("ssh",fiftyvms[[1]])
plan(cluster, workers = fiftyvms)
Error: check_ssh_set(x) is not TRUE
```

**Comment by MarkEdmondson1234** [comment]
Are you authenticating with different keys than normal? Try an additional step where you run the VMs through the gce_ssh_setup() function worth your SSH keys and user name specified.

**Comment by mgahan** [comment]
Thanks for the quick reply! I went ahead and used the `gce_ssh_setup` function, and I think the keys look to be uploaded correctly, but I am still having problems with the `plan` function for some reason.

```
> for (i in 1:3) {
+ 	gce_ssh_setup(
+ 		 fiftyvms[[i]], 
+ 		 username="mgahan",
+ 		 key.pub="~/.ssh/google_compute_engine.pub",
+ 		 key.private = "~/.ssh/google_compute_engine")
+ }
2017-06-11 11:33:13> Using ssh-key files given as ~/.ssh/google_compute_engine.pub / ~/.ssh/google_compute_engine
2017-06-11 11:33:21> Public SSH key uploaded to instance
2017-06-11 11:33:21> Using ssh-key files given as ~/.ssh/google_compute_engine.pub / ~/.ssh/google_compute_engine
2017-06-11 11:33:29> Public SSH key uploaded to instance
2017-06-11 11:33:29> Using ssh-key files given as ~/.ssh/google_compute_engine.pub / ~/.ssh/google_compute_engine
2017-06-11 11:33:38> Public SSH key uploaded to instance
> plan(cluster, workers = fiftyvms)
Error: check_ssh_set(x) is not TRUE
```

**Comment by MarkEdmondson1234** [comment]
I forgot to add this bit sorry. You need to reassign the gce_ssh_setup result back to the vm:  

`fiftyvms <- lapply(fiftyvms, gce_ssh_setup, username ="mark", etc.)`

**Comment by mgahan** [comment]
Awesome! Looks like now I can get past the `plan` function, but unfortunately i run into problems at the next step:

```
> ## the action you want to perform via cluster
> my_single_function <- function(x){
+ 	out <- 3*x
+   return(out)
+ }
Warning messages:
1: closing unused connection 5 (<-localhost:11494) 
2: closing unused connection 4 (<-localhost:11100) 
3: closing unused connection 3 (<-localhost:11434) 
> all_results <- future_lapply(1:3, my_single_function)
Error: is.character(workers) || is.numeric(workers) || inherits(workers,  .... is not TRUE
> fiftyvms
```

**Comment by MarkEdmondson1234** [comment]
Hmm, I'll have to look when I'm back. The warnings are just from a previous future session   Try it locally first with `plan(multisession)` to make sure it isn't the function.  (Which will run it locally on your multi cores)

**Comment by mgahan** [comment]
Good idea. It does seem to work with `plan(multisession)`, but still having trouble getting it to work with the instances.

```
> plan(multisession)
> my_single_function <- function(x){
+ 	out <- 3*x
+   return(out)
+ }
> all_results <- future_lapply(1:3, my_single_function)
> all_results
[[1]]
[1] 3

[[2]]
[1] 6

[[3]]
[1] 9
```

With instances...

```
> plan(cluster, workers = fiftyvms)

> my_single_function <- function(x){
+ 	out <- 3*x
+   return(out)
+ }
> all_results2 <- future_lapply(1:3, my_single_function)
Error: is.character(workers) || is.numeric(workers) || inherits(workers,  .... is not TRUE
```

**Comment by MarkEdmondson1234** [comment]
@HenrikBengtsson I wonder if you have an idea about this?

I have confirmation it works with others and for me locally, so I think I'm missing something obvious.

**Comment by HenrikBengtsson** [comment]
Thanks for letting me know.  I can reproduce this without googleComputeEngineR as:
```r
> library("future")
> cl <- parallel::makeCluster(2L)
> workers <- unclass(cl)
> plan(cluster, workers = workers)
> y <- future_lapply(1:2, FUN = identity)
Error: is.character(workers) || is.numeric(workers) || inherits(workers,  .... is not TRUE
```
The culprit is basically:
```r
> library("future")
> cl <- parallel::makeCluster(2L)
> workers <- unclass(cl)
> plan(cluster, workers = workers)
> nbrOfWorkers()
Error: is.character(workers) || is.numeric(workers) || inherits(workers,  .... is not TRUE
```
I'll investigate and see if I can fix this.  The workaround is to use `workers = as.cluster(workers)` as in:
```r
> plan(cluster, workers = as.cluster(workers))
> nbrOfWorkers()
[1] 2
```
or in your case:
```r
plan(cluster, workers = as.cluster(fiftyvms))
```
This was actually in the documentation before [I claimed it wasn't needed anymore back in March](https://github.com/cloudyr/googleComputeEngineR/pull/46) :/  Sorry about that.

**Comment by MarkEdmondson1234** [comment]
Great, thanks for looking @HenrikBengtsson !  I'll change the documentation for now and wait for updates.

**Comment by mgahan** [comment]
Excellent! Thanks guys! This is awesome. One question - how is `future_lapply` interacting with the docker container? Is it through a `docker exec` command?

**Comment by MarkEdmondson1234** [comment]
Hi @mgahan - its via a `docker run`, you can see the code [here](https://github.com/cloudyr/googleComputeEngineR/blob/master/R/future.R).
