### ISSUE TITLE
don't get same shell when accessing vm via ssh 

### ISSUE THREAD

**Issue by agilebean** [cloudyr/googleComputeEngineR#58]
i would be _very_ grateful for any concrete tip to solve this:

1. create vm by gce_vm()
2. log into vm via gce_ssh_browser()
i expected to have linux commands available like apt-get but get instead: command not available.

how can i get the "normal" linux shell which you get when creating the vm within the google compute engine ui ("create vm instance" | "SSH")?

this is important because some things get installed easier on linux command line like e.g. for installing devtools, you need to do:
sudo apt-get -y install libcurl4-gnutls-dev libxml2-dev libssl-dev

**Comment by IronistM** [comment]
This probably because the operating system you have deployed doesn't have `apt`; maybe it's [COS](https://cloud.google.com/container-optimized-os/docs/) (?). If you are deploying a vm using template or docker you can add these installations within the Dockerfile, however like

```FROM rocker/shiny
MAINTAINER Manos Parzakonis (parzakonis.m@gmail.com)

# install R package dependencies
RUN apt-get update && apt-get install -y \
libssl-dev \
## clean up
&& apt-get clean \ 
&& rm -rf /var/lib/apt/lists/ \ 
&& rm -rf /tmp/downloaded_packages/ /tmp/*.rds

...
```

**Comment by MarkEdmondson1234** [comment]
Yep @agilebean as @IronistM says perhaps you are using a Docker container VM, in which case they restrict things like `apt-get` - as its in a Docker container you may be wanting to use `apt-get` within the docker container, although then you may be best making a `Dockerfile` for more control.

Something like `docker exec -it rstudio bash` will drop you within the container, that usually runs Ubuntu or similar with all normal tools.  But if you are making changes to RStudio container its probably easier to log in via the RStudio menu to open a shell within the container from there.  Or, perhaps you don't want a Docker container at all, in which case use the more direct `gce_vm_create` or similar.

Let us know what you are trying to achieve, and we may be able to help further :)

**Comment by agilebean** [comment]
Thanks @MarkEdmondson1234 I think you might be right. 
I couldn't find any documentation on gce_vm(template = "rstudio", ...) but I read some hints on Dockerfile (sorry @IronistM I don't know how to access the Dockerfile)

Thank you for your question, it really made me think - here's the answer:
I want to...
1. get Rstudio Server running on the Google Cloud Compute engine
2. have direct access to the Ubuntu/Demian installation to run Python scripts, use homebrew or pip

I tried to achieve this that starting directly in the Google Cloud and reached goal 2 quickly but not goal 1, i.e. couldn't get Rstudio Server running despite strictly following instructions - see https://stackoverflow.com/questions/44914643/rstudio-server-not-running-on-google-cloud-compute-engine.
So I tried to achieve the same goals through the googleComputeEngineR library. It is super easy to use and I achieved goal 1 quickly - thanks a lot @MarkEdmondson1234 it is a great piece of work. But now I'm stuck with goal 2.
Unfortunately, the `docker exec -it rstudio bash` only returned `command not found` when executed on the ssh terminal. 
So now the question is how I can drop to Ubuntu within the container in an effective way?
If I use the Docker container what advantages does it have?

Thanks in advance!

**Comment by MarkEdmondson1234** [comment]
Ok cool, make sure you read at [least this page on the website](https://cloudyr.github.io/googleComputeEngineR/articles/creating-vms.html#templated-container-based-vms) and maybe the page on [Docker](https://cloudyr.github.io/googleComputeEngineR/articles/docker.html), but essentially the quickest way to achieve 2. would be to log into the RStudio Server from 1), then select `Tools > Shell` in the RStudio menu which will give you the shell within the Docker container running RStudio (which by default is [`rocker/rstudio`](https://hub.docker.com/r/rocker/rstudio/) )

However, if the Docker container restarts you will need to install the libraries again as the Docker container freezes state (this is a feature not a bug :) ), so we would advise you do your apt-install commands in your own Dockerfile.  Some examples are in the library [here](https://github.com/cloudyr/googleComputeEngineR/tree/master/inst/dockerfiles) but see also the website such as the example workflows that walk through making your file, [like this one.](https://cloudyr.github.io/googleComputeEngineR/articles/single-scheduler.html#how-to-customise-your-own-rstudio-server)
