### ISSUE TITLE
Question: Massively parallel processsing

### ISSUE THREAD

**Issue by mgahan** [cloudyr/googleComputeEngineR#61]
This is a really cool tutorial you have made. I do have a question about speeding up the machine creation time. So this line of code creates 50 machines sequentially:

```
## start up 50 VMs with R base on them (can also customise via Dockerfiles using gce_vm_template instead)
fiftyvms <- lapply(vm_names, gce_vm, predefined_type = "n1-standard-1", template = "r-base", scheduling = preemptible)
```

Would there by a way to do the same but with instance groups and instance templates? Would all of the machines be created at the same time rather than sequentially?

Thanks again,
Mike

**Comment by MarkEdmondson1234** [comment]
Good question, I haven't implemented instanceGroups yet but I will open an issue to do so.

For now, the function `gce_vm` is a wrapper of [`gce_vm_create`](https://cloudyr.github.io/googleComputeEngineR/reference/gce_vm_create.html) with some helpful defaults, but one of those is to wait for the VM to launch before returning.  

`gce_vm_create` (and [`gce_vm_container`](https://cloudyr.github.io/googleComputeEngineR/reference/gce_vm_container.html)) will start the process and return immediately, so actually is more suited to lots of VMs launching at once.

**Comment by mgahan** [comment]
awesome! thanks mark
