### ISSUE TITLE
Can't make custom cpus/memory vm

### ISSUE THREAD

**Issue by Blaza** [cloudyr/googleComputeEngineR#63]
When I call, for example,
```r
gce_vm("vm", cpus = 6, memory = 5632)
```
I should get a custom instance with 6 cpus and 5.5 gb memory. However, logging into the gce console and
checking the details of the created instance, I see that the instance is instead `f1-micro`, i.e. the default `predefined_type` of `gce_vm_create`. Am I missing something here or is this a bug?

Taking a quick glance, I think there is possibly a problem in the call to the `gce_make_machinetype_url` function inside `gce_vm_create`. Namely, in `gce_vm_create` it writes:
```r
  ## make machine type
  machineType <- gce_make_machinetype_url(predefined_type = predefined_type,
                                          cpus = cpus,
                                          memory = memory,
                                          zone = zone)
```
and then in `gce_make_machinetype_url` it checks if `predefined_type` is  `missing` in order to create a URL with custom cpu/memory values. However, while `predefined_type` is missing in `gce_vm_create`, it isn't missing in `gce_make_machinetype_url` as we called it giving the default `predefined_type`.

Again, I just took a quick glance at the code, I may be completely missing the point.

PS Thanks for the lovely package!

**Comment by MarkEdmondson1234** [comment]
Hmm I'll look at this.  In the meantime does it work correctly if using `gce_vm_create`?

**Comment by MarkEdmondson1234** [comment]
Note to self, never use `missing` again.

**Comment by Blaza** [comment]
Nope, still the same. It makes sense as you are calling it with `...` from `gce_vm` so it keeps missing `predefined_type`, but later the default is passed to `gce_make_machinetype_url`.

Can you suggest a temporary workaround for this issue until the package is updated?
I guess I could pass `predefined_type = "custom-<cpus>-<memory>"` to `gce_vm`.
Is there a better solution?

**Comment by MarkEdmondson1234** [comment]
Does passing a custom string work for machine type? That's new to me if so, may be better way to deal with it. Otherwise I will just need to fix the bug.

**Comment by Blaza** [comment]
This worked for me nicely
```r
gce_vm("vm", predefined_type = "custom-6-5632")
```

It overrides the default value for `predefined_type` in `gce_vm_create` and makes it into what `gce_make_machinetype_url` would set it by (line 27 in R/machineType.R)
```r
out <- sprintf("zones/%s/machineTypes/custom-%s-%s", zone, cpus, memory)
```
and indeed it makes an instance with desired cpus and memory.

**Comment by MarkEdmondson1234** [comment]
Ok - cool! I may just document this then and get rid of the arguments. Any problems with that do you think?

**Comment by MarkEdmondson1234** [comment]
Ok, I should have known this looking at the code I wrote ;)  I will fix this now.

**Comment by MarkEdmondson1234** [comment]
Ok, try the GitHub version now to see if it works as expected the old way.  Both ways will work.

**Comment by Blaza** [comment]
Yep, everything works as expected.
