### ISSUE TITLE
can't create rstudio-server-gpu VM

### ISSUE THREAD

**Issue by goldingn** [cloudyr/googleComputeEngineR#70]
I have authorised GPU quota on cloud compute, but trying to initialise a vm with the `"rstudio-server-gpu"` image errors:
```r
rss_gpu <- gce_vm(template = "rstudio",
                  name = "rstudio-server-gpu",
                  username = "nick",
                  password = "",
                  predefined_type = "n1-standard-16",
                  acceleratorCount = 2L)
```
```
2017-09-15 11:30:05> Creating template VM
Request Status Code: 400
Error in checkGoogleAPIError(req) : 
  JSON fetch error: Instances with guest accelerators do not support live migration.
``` 

I can create and restart CPU instances just fine, and manually create a GPU instance via the console.

Any ideas how to fix this?

<details>
I'm using version 0.1.0.9002 (cloudyr fork, master branch, commit 8d6531bc2447) and this is my session info:
```
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin16.7.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googleComputeEngineR_0.1.0.9002

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12          rstudioapi_0.6.0.9000 magrittr_1.5          devtools_1.13.3       xtable_1.8-2         
 [6] R6_2.2.2              httr_1.3.1            globals_0.10.2        tools_3.4.1           parallel_3.4.1       
[11] googleAuthR_0.5.1     withr_2.0.0           tfruns_0.9.1          htmltools_0.3.6       openssl_0.9.7        
[16] yaml_2.1.14           assertthat_0.2.0      digest_0.6.12         crayon_1.3.2.9000     tensorflow_1.3.1     
[21] shiny_1.0.5           codetools_0.2-15      testthat_1.0.2.9000   curl_2.8.1            memoise_1.1.0        
[26] mime_0.5              compiler_3.4.1        reticulate_1.1        jsonlite_1.5          future_1.6.1         
[31] httpuv_1.3.5          listenv_0.6.0
```
</details>

**Comment by MarkEdmondson1234** [comment]
Its a weird error, but I think you need to add the `use_beta=TRUE` flag.  Or perhaps GPUs are only supported in certain zones.  

Note its very experimental.

**Comment by goldingn** [comment]
Adding `use_beta=TRUE`, I still get the error (plus a little warning):
```
2017-09-18 11:18:06> Creating template VM
Request Status Code: 400
Error in checkGoogleAPIError(req) : 
  JSON fetch error: Instances with guest accelerators do not support live migration.
In addition: Warning message:
In (function (name, predefined_type = "f1-micro", image_project = "debian-cloud",  :
  This is using the beta version of the Google Compute Engine API and may not work in the future.
```

GPUs are definitely available in asia-east-a (which I'm using) though perhaps they are using a different API there. Which zone have you run these on?

Yeah, I appreciate this is experimental (as is Google's API for GPUs). Thanks for your work on this - it'll be incredibly useful!

**Comment by MarkEdmondson1234** [comment]
Does this occur for new instances or for an existing one?  It may be that the zone you launched a previous GPU enabled VM has had a maintenance window, and it got closed down?

I've been launching them in US zones.

**Comment by goldingn** [comment]
It occurs when creating new instances. I can connect to a GPU-enabled instance (created via the cloud console web app), and I can create a non-GPU enabled instance, but I can't create a GPU-enabled instance.

[This section](https://cloud.google.com/compute/docs/gpus/add-gpus#host-maintenance) of the Google cloud compute docs seems relevant, though I have no idea how to configure those settings!

**Comment by goldingn** [comment]
Oh, [this](https://cloud.google.com/compute/docs/instances/setting-instance-scheduling-options#settingoptions) looks like the relevant config information

**Comment by MarkEdmondson1234** [comment]
Ok, it looks like a config flag is on for GPU instances that shouldn't be, will check.

**Comment by MarkEdmondson1234** [comment]
This works via the code in https://github.com/cloudyr/googleComputeEngineR/issues/101 and will look to improve the template so its much easier
