### ISSUE TITLE
Site cant be reached after instance stopped

### ISSUE THREAD

**Issue by ErezLo** [cloudyr/googleComputeEngineR#71]
Hey

I've created an instance with the rstudio template.

```
library(googleComputeEngineR)

project <- gce_get_project()

## creating a google colud VM Instance
vmnew <- gce_vm(template = "rstudio-hadleyverse",
             name = "rstudio-teamnew",
             username = "mark", password = "mark1234",
             predefined_type = "n1-highmem-2")

## starting and stopping instances
## getting ALL instances statuses
gce_list_instances()
```

Once I start the VM its working perfectly and I login to R and everything is fine.
Once I stop it and then later start it again (with a new external IP), I cannot get the login screen any more.

just the site cant be reached..
Any idea for possible causes ?

I feel like when restarting the instance something is missing.

Thanks

**Comment by MarkEdmondson1234** [comment]
Can I check what version you are using?  The new one on CRAN (0.2.0) may solve this for you, as it fixed this bug https://github.com/cloudyr/googleComputeEngineR/issues/30

**Comment by ErezLo** [comment]
You are absolutely right.
I was just about to close this.
After updating to 0.2 the issue was solved.

Thank you
