### ISSUE TITLE
Authentication of remote instance

### ISSUE THREAD

**Issue by MilesAheadAlso** [cloudyr/googleComputeEngineR#75]
Mark, I'm not actually sure this is the issue. But below is my code and the error.
`vm_names <- paste0("test-",1:totInstances)

## specify the cheapest VMs that may get turned off
preemptible = list(preemptible = TRUE)

## start up VMs with R base on them (can also customise via Dockerfiles using gce_vm_template instead)
myGCEinstances <- lapply(vm_names, gce_vm, 
                         predefined_type = "n1-standard-8", 
                         template = "rstudio", 
                         scheduling = preemptible, 
                         username="rstudio", password="password")
myGCEinstances <- lapply(myGCEinstances, gce_ssh_setup)
plan(cluster, workers = as.cluster(myGCEinstances), future.debug = TRUE, future.progress = TRUE)
`
The creation of the instances works perfectly. Since this is essentially the code in your blog I'm wondering what I am doing incorrectly.

`> plan(cluster, workers = as.cluster(myGCEinstances), future.debug = TRUE, future.progress = TRUE)
2017-10-06 12:48:54> External IP for instance test-1 : 35.184.11.53
Warning: Permanently added '35.184.11.53' (RSA) to the list of known hosts.
also installing the dependencies ‘digest’, ‘globals’, ‘listenv’

2017-10-06 12:49:13> External IP for instance test-2 : 35.194.39.142
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:89ZcyfvsEgsmEv8j5gDciDWaGajxO+HUK65kJhJPkqs.
Please contact your system administrator.
Add correct host key in /tmp/RtmpJtdeIl/hosts to get rid of this message.
Offending ECDSA key in /tmp/RtmpJtdeIl/hosts:1
  remove with:
  ssh-keygen -f "/tmp/RtmpJtdeIl/hosts" -R 35.194.39.142
Password authentication is disabled to avoid man-in-the-middle attacks.
Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
Port forwarding is disabled to avoid man-in-the-middle attacks.
also installing the dependencies ‘digest’, ‘globals’, ‘listenv’

Error: reached elapsed time limit`

**Comment by MarkEdmondson1234** [comment]
I think this is to do with the SSH setup step - thats important as it generates the keys, it looks like you can log in but not do anything at the moment which points to SSH key not verified

This step:

```r
## add any ssh details, username etc.
fiftyvms <- lapply(fiftyvms, gce_ssh_setup)
```

You can pass other arguments to [`gce_ssh_setup` ](https://cloudyr.github.io/googleComputeEngineR/reference/gce_ssh_setup.html) as needed if your username is different, SSH private keys not in default gcloud position, etc.

Are you relying on the `gcloud` default SSH keys or generating your own?

**Comment by MilesAheadAlso** [comment]
Hi Mark

I guess I need the idiots guide to using your packages. I'm new to docker
and google cloud, so I am probably not doing a whole bunch of stuff you
take for granted given your knowledge.

What I would like to do is:
- Create several instances that have r-base loaded
- Install around 20 packages to do statistical forecasting (they do not
appear to be installed as standard)
- Take the historical data set and split it across the instances
- Each instance calculate the best fit forecasting method for each time
series in its data set
- Collate the best fit results and forecasts

I can do all of this manually by first creating an instance, installing R
and RStudio, installing the packages I need, and copying over an R script.
I then create several instances using this first instance as an image. I
then go into each instance and run the R script which writes the results to
a file. I then have to collate the results from each instance.

I'd like to be able to use your packages and docker to automate this
process. I'm asking if you have some step-by-step instructions for this.

Regards
Trevor

**Comment by MarkEdmondson1234** [comment]
This just says to me the documentation isn't good enough yet, so I'll look to update it ASAP so you can get it working.  I know others are using it in production and appreciate it, so its worthwhile doing.  It is a combo of lots of new concepts if you're not used to Docker etc. and its been a bit of a moving target as I myself find better workflows so I'll try to communicate that in the docs.

**Comment by MilesAheadAlso** [comment]
Much appreciated Mark. Of course it may be best to create a docker once I
have loaded all the packages I need for starts forecasting

**Comment by MilesAheadAlso** [comment]
Hi Mark

I came across doAzureParallel that has a nice approach that I would like to
replicate with your package. I have a data set with historical sales by
month for the past 5 years for over 2500 items for which I want to generate
a statistical forecast for the next 6 months. What doAzureParallel allows
me to create N instances and then throw the entire data set at the cluster
while it take care of scheduling the jobs for each item across the VMs in
the cluster. In other words I do not need to first split the data into
roughly equal chunks and then send those chunks to the VMs.

I interpret the way I need to use GoogleComputeEngineR is to in fact split
the data and send different data packages to each of the VMs created. In my
example above, if I had 5 VMs I would split the historical sales into 5
packages each containing 500 items.

I came across your example of remote clusters (
https://cran.r-project.org/web/packages/googleComputeEngineR/vignettes/remote-cluster.html),
but I cannot work out how to tell the cluster to iterate across the data
set by item. Your code example shows the following:

## make a big function to run asynchronously
f <- function(my_data, args){
   ## ....expensive...computations
   result
}
## send to cluster result %<-% f(my_data)


I cannot see how I would know how to parse the data within this code
so that I would run a forecast for a single item, and then iterate to
the next item. Of course I mean this in parallel.

Using doAzureParallel I can write:

results <- foreach(i = 1:nItems) %dopar% {
  itemName <- ForecastItems[i]
  itemHistory <- subset(History, ForecastItem == itemName)
  expensive_function(itemName, itemHistory, fcstArgs)
}

I would prefer to use GCE and your R package for many reasons, but I need
to be able to distribute many jobs to a cluster. I'd really appreciate you
sharing some code on how to do this using your package, if it is possible.

**Comment by MarkEdmondson1234** [comment]
I have updated the documentation here https://cloudyr.github.io/googleComputeEngineR/articles/massive-parallel.html

I also made it easier to use `gce_vm_template` in the workflow by adding a `wait = FALSE` flag.

Please let me know any feedback on where the documentation could be clearer, and if it works with your use case

**Comment by MilesAheadAlso** [comment]
Thanks Mark

On Nov 10, 2017 08:55, "Mark" <notifications@github.com> wrote:

I have updated the documentation here https://cloudyr.github.io/
googleComputeEngineR/articles/massive-parallel.html

I also made it easier to use gce_vm_template in the workflow by adding a wait
= FALSE flag.

Please let me know any feedback on where the documentation could be
clearer, and if it works with your use case

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cloudyr/googleComputeEngineR/issues/75#issuecomment-343479291>,
or mute the thread

**Comment by mike-lawrence** [comment]
I'm encountering the same warning too. I'm following the [Massively Parallel Processing guide](https://cloudyr.github.io/googleComputeEngineR/articles/massive-parallel.html) and running this:
```
Sys.setenv("GCE_AUTH_FILE"="axemnimbus.json")
Sys.setenv("GCE_DEFAULT_PROJECT_ID"="axemnimbus")
Sys.setenv("GCE_DEFAULT_ZONE"="northamerica-northeast1-a")
library(future)
library(googleComputeEngineR)
vms = gce_vm_cluster() #presumes you have used ssh-keygen to create ~/.ssh/google_compute_engine.pub
```
When I ran it the first time, everything went fine, but after deleting the generated instances and trying again, I get the "REMOTE HOST IDENTIFICATION HAS CHANGED!" warning.

**Comment by mike-lawrence** [comment]
I solved this by simply restarting R. It seems that the ssh handshake writes to a tmp file that persists during a session, so if you have deleted an instance and want to make a new one, you have to restart R to clear that tmp file.
