### ISSUE TITLE
Choosing a Container

### ISSUE THREAD

**Issue by thenextbillgates** [cloudyr/googleComputeEngineR#76]
Hi Mark,

Fantastic work on this package - we are tinkering with it and it could be part of a very exciting ML extension of our organization.

I've read through the docs thoroughly. I can create instances, get my SSH keys, execute commands, it all works. I have also created my own Docker image based on r-base with added packages pre-installed.

Using your package, running gce_vm() creates or turns on a VM with the r-base docker image loaded but not running.

Running plan(cluster, workers = as.cluster(myVMs)) will then cause the VM to start a container based on r-base.

So here's my question: How do I tell R to use MY docker image rather than r-base?

I can start the container manually, such as by using gce_ssh("docker run....") but I still don't understand how to tell R to use that container rather than starting up an r-base container.

Can you point me to the right documentation/function/blog/anything to help me out?

Thanks!

**Comment by MarkEdmondson1234** [comment]
Hi @thenextbillgates sounds great, do let me know any other feedback to make it as easy as possible to work with.

This is a documentation issue, but fortunately another user worked it out that I quickly copy-paste here:

```r
plan(cluster, workers = as.cluster(
  VM_List, 
  docker_image="gcr.io/my-rstudio",
  rscript=c("docker", "run", c("--net=host","--shm-size=13G"),
			"gcr.io/my-rstudio", 
			"Rscript")))
```

I'm going to update the docs as requested also here https://github.com/cloudyr/googleComputeEngineR/issues/75 to reflect this.

 In essence its documenting this function:

https://github.com/cloudyr/googleComputeEngineR/blob/d460bba0ca4ee206b361674c90135482f04db340/R/future.R#L4-L14

...which is what is happening when you use the `as.cluster` argument from `library(future)`

**Comment by MarkEdmondson1234** [comment]
@thenextbillgates did this solve your issue?

**Comment by thenextbillgates** [comment]
Hey @MarkEdmondson1234, yes it did, thanks!!
