### ISSUE TITLE
Can't open RStudio in a browser (external IP address won't load)

### ISSUE THREAD

**Issue by mlsethi** [cloudyr/googleComputeEngineR#82]
Hi there, I'm new to both Google Cloud Platform and googleComputeEngineR, and hoping to get some help resolving a basic issue. 

I've followed the instructions for getting RStudio to run on Google Compute Engine that are posted here: https://cloudyr.github.io/googleComputeEngineR/articles/installation-and-authentication.html 
and here: http://code.markedmondson.me/launch-rstudio-server-google-cloud-in-two-lines-r/
I've also made sure HTTP traffic is allowed and set a firewall rule that opens port 8787. 

When I run the following code:

> vm <- gce_vm(template = "rstudio",
>              name = "my-instance",
>              username = "myusername", password = "mypassword",
>              predefined_type="n1-highmem-2")
> 

I get the following:

> 2017-11-05 16:43:52> VM previously created but not running, starting VM
> 2017-11-05 16:43:53> Checking operation...PENDING
> 2017-11-05 16:43:56> Operation running...
> 2017-11-05 16:43:59> Operation running...
> 2017-11-05 16:44:06> Operation complete in 8 secs
> 2017-11-05 16:44:07> VM running
> 

The first odd thing is that the external IP address for RStudio isn't printed, but I can run gce_get_external_ip("my-instance", verbose = TRUE) and get that, or just find it in the instance info on Google Cloud Platform. But when I try to load the IP address, I get a "failed to open page" error and my browser says it can't contact the server. Waiting even half an hour makes no difference.

Any advice would be appreciated. Thanks!

**Comment by mlsethi** [comment]
Update: I still don't know why my original code didn't work, but starting an instance using a custom rstudio build with the tidyverse installed does work:

> tag <- gce_tag_container("google-auth-r-cron-tidy", project = "gcer-public")
> vm <- gce_vm("rstudio-cron-googleauthr", 
>              predefined_type = "n1-standard-1",
>              template = "rstudio", 
>              dynamic_image = tag, 
>              username = "myusername", 
>              password = "mypassword")

However, now I'm running into a new issue. I need to install JAGS, and running apt-get install jags or yum install jags from an SSH session returns "command not found". Any thoughts? Thanks so much!

Edited to add: I received the following note from a friend, in case this helps: "what’s likely happening is that when you SSH you’re SSH-ing into a Docker image, which is running some weird very limited version of linux wherein you can’t install anything." 

Thanks again for any advice you can offer! I'm really new to all this and am just trying to get a slow Bayesian model to run in the cloud. :)

**Comment by MarkEdmondson1234** [comment]
Your friend is partly right :)

The limited version of linux is the one running Docker, which pretty much only runs Docker, and not apt-get etc.

But the Docker container itself runs full blown Ubuntu, so within the Docker container you can install things just fine.

When you SSH in you are logging in to the machine running docker.  To run inside Docker you need `docker exec -it rstudio bash` which will drop you in a shell within the Rstudio docker.

But, the easiest way is to log in to your RStudio server instance, then use Rstudio's menu to access the terminal.  Since you are within the Docker container there, you will be able to install what you need.

**Comment by MarkEdmondson1234** [comment]
As to your first issue, I can run your code and it still works ok for me, that makes me think its perhaps previous code that is causing your issue.   How did you authenticate, via JSON or via `gce_auth()` ?

**Comment by mlsethi** [comment]
Thanks, Mark! I actually did install jags through the RStudio terminal after I posted, but the installation of the rjags package still failed, with the same error messages. It's good to know that that's where I should be installing jags, though. I'm guessing I need to work on getting RStudio to figure out where to find jags. 

I used JSON to authenticate.

**Comment by MarkEdmondson1234** [comment]
You could at least use `apt-get` via the RStudio terminal though I guess - its a different error message than "command not found"?  I don't know Jags so it may be you need to look at other help, although I would suggest that its better to create a Dockerfile with your install steps installed, then follow the guide for your own custom environment.  A helper for that is https://github.com/o2r-project/containerit

**Comment by MarkEdmondson1234** [comment]
I put a guide to custom environments here https://cloudyr.github.io/googleComputeEngineR/articles/docker.html#build-triggers

**Comment by mlsethi** [comment]
Thanks again! I uploaded the JAGS source folder into my Home directory in RStudio server and ran sudo apt-get update in the terminal before trying to install jags and then rjags again, and now all is well! Just posting this in case anyone else has a similar issue. Cheers!

**Comment by MarkEdmondson1234** [comment]
Great thanks :)

**Comment by jmpineiro** [comment]
Hello Mark, 
I want to work with Rstudio server on Google Cloud Platform, but I can't connect to Rstudio server with the external IP from my browser (neither on firefox nor Chrome ). 

I reinstalled Rstudio server on my VM instance and cheked the instalation without any error, using: $ sudo rstudio-server verify-installation

I created the ssh key and allowed the http and https Firewalls on Compute Engine/ VM instance, 
and also allowed the access of all API and the connection with serial port too.

Also, I ran this: $ wget localhost:8787   , then i tried to connect by the external IP on my browser without success
Then I ran : $ sudo gcloud compute firewall-rules create allow-rstudio --allow=tcp:8787 
and again... I cant connect with the IP 

I would really appreciate any help or suggestion
thanks in advance!!!!

sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS
Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0
locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
loaded via a namespace (and not attached):
[1] compiler_3.4.3

**Comment by MarkEdmondson1234** [comment]
Hi @jmpineiro have you tried the steps as outlined in the video here?: https://cloudyr.github.io/googleComputeEngineR/

> I reinstalled Rstudio server on my VM instance and cheked the instalation without any error, using: $ sudo rstudio-server verify-installation

This sounds like you are not using `gce_vm(template = "rstudio")` and installing on the base VM?

> I created the ssh key and allowed the http and https Firewalls on Compute Engine/ VM instance,
and also allowed the access of all API and the connection with serial port too.

SSH key is good, but you should not need to create the firewalls as of version `0.2.0`

> Also, I ran this: $ wget localhost:8787 , then i tried to connect by the external IP on my browser without success

If using the Docker instance that is launched via `gce_vm` then it maps to port 80 e.g. no need to use 8787

> Then I ran : $ sudo gcloud compute firewall-rules create allow-rstudio --allow=tcp:8787
and again... I cant connect with the IP

This sounds like you are using the `gcloud` tool, not this library.  If you want to use that method you need to open an issue with them, but I would suggest looking at the video to see how its done with this library.

**Comment by jmpineiro** [comment]
Hi Mark, thanks for your suggestions.
Yes Mark, I used that video to create the VM with success, but then I cant
connect with IP address.
Also I used: gce_vm(template = "rstudio")
I do not know if I am using a Docker instance, How can I know it?

Because Im cannot connect with Rstudio server by IP, I resolve to ran R on
the Linux console of  the VM, but I really want ro ran Rstudio server...

I really appreciate any suggestions or guidelines...



2017-12-16 9:54 GMT-03:00 Mark <notifications@github.com>:

**Comment by MarkEdmondson1234** [comment]
Could you show the code you used, then the `sessionInfo()`  command to show what versions of the packages you are using?  Also make sure you are using the auto-authentication methods.

**Comment by ben519** [comment]
Just wrestled with this issue. Here's what worked for me -

1. Log in to the [google cloud console](https://console.cloud.google.com/)
2. Go to the Compute Engine page
3. Locate and click on the rstudio instance (or whatever you named it) from the list
4. Edit > Firewalls > check both boxes

<img width="159" alt="screen shot 2018-09-05 at 12 43 31 pm" src="https://user-images.githubusercontent.com/723099/45110986-6610d000-b109-11e8-868b-7ce3ebd89a02.png">

5. This is where I got hung up. In a new browser tab, go to http://your-external-ip-address-here **NOT** https://your-external-ip-address-here.  Not sure why this is the case, but it's what works for me.

**Comment by MarkEdmondson1234** [comment]
Thanks @ben519 !  The port opening you are doing in step 4 _should_ be done on the first boot, but will check again if that is the case.  The http vs https makes sense as RStudio is mapped to 80, not 443 where 80 is assoicated with http and 443 associated with https

**Comment by markusMiksa1304** [comment]
even these steps do not help : 
no connection to http://<ip>:8787

**Comment by MarkEdmondson1234** [comment]
You have no IP address assigned yet it seems, did the console return one when you started up the VM?


________________________________

**Comment by markusMiksa1304** [comment]
vm <- gce_vm( template = "rstudio",
              name = "mm-rstudio-datalab-m5",
              zone = "europe-west4-b",
              username = "rstudio", password = "rstudio",
              predefined_type = "n1-highmem-2",
              network = "datalab-network"
)

gce_list_instances()
… that gives the ip
==Google Compute Engine Instance List==
                                  name   machineType     status           zone     externalIP   creationTimestamp
3                mm-rstudio-datalab-m5  n1-highmem-2    RUNNING europe-west4-b    34.90.27.83 2019-08-14 04:30:38
4 rstudio-server-pro-for-bigquery-1-vm n1-standard-1 TERMINATED europe-west4-b No external IP 2019-08-12 05:31:34


browseURL("http://34.90.27.83:8787/")   ….> no connection

When i use the  commercial (expensive) rstudio-server-pro-for-bigquery-1-vm n1-standard-1
from the marketplace .. everything works as expected

I compared the firewall- rules  … found no significant difference …

Very strange ☹

Best Regards
  Markus


Von: Mark [mailto:notifications@github.com]
Gesendet: Mittwoch, 14. August 2019 13:27
An: cloudyr/googleComputeEngineR <googleComputeEngineR@noreply.github.com>
Cc: Markus Miksa <markus.miksa@telefonica.com>; Comment <comment@noreply.github.com>
Betreff: Re: [cloudyr/googleComputeEngineR] Can't open RStudio in a browser (external IP address won't load) (#82)

You have no IP address assigned yet it seems, did the console return one when you started up the VM?


________________________________

**Comment by MarkEdmondson1234** [comment]
Don’t use username / password = rstudio - that’s an existing username and will cause an error.


________________________________

**Comment by markusMiksa1304** [comment]
vm <- gce_vm( template = "rstudio",
              name = "mm-rstudio-datalab-m8",
              username = "markus", password = "milkaMaus6",
              predefined_type = "n1-highmem-2",tags="mm2rstudio"

)

Same procedure .. same result: No connection ..

Best Regards

(does it work on Your machine ?)


Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Mark <notifications@github.com>
Gesendet: Wednesday, August 14, 2019 1:49:12 PM
An: cloudyr/googleComputeEngineR <googleComputeEngineR@noreply.github.com>
Cc: Markus Miksa <markus.miksa@telefonica.com>; Comment <comment@noreply.github.com>
Betreff: Re: [cloudyr/googleComputeEngineR] Can't open RStudio in a browser (external IP address won't load) (#82)

Don’t use username / password = rstudio - that’s an existing username and will cause an error.


________________________________

**Comment by markusMiksa1304** [comment]
Your code works fine
sorry:  my mistake
i expected rstudio on port 8787 - like the commercial rstudio-server-pro

i m not sure if its possible to configure a vm listening on 8787 - but thats no problem for me

1000 times:  thank You for Your code - and for Your fast reply

**Comment by MarkEdmondson1234** [comment]
Ah great yes it maps the port in the template from 8787 to 80.

If you want more customization that’s possible via the gce_vm_container or gce_vm_create functions launching your own Docker and/or cloud-config files


________________________________
