### ISSUE TITLE
Troubles following persistent storage guide

### ISSUE THREAD

**Issue by ignacio82** [cloudyr/googleComputeEngineR#83]
I'm having troubles following the guide for persistent storage guide. This is what I'm doing:

```
project <- "imgc-185017"
zone <- "us-east1-b"
account_key <- "IMGoogle.json"
Sys.setenv(GCE_AUTH_FILE = account_key,
           GCE_DEFAULT_PROJECT_ID = project,
           GCE_DEFAULT_ZONE = zone)
library(googleCloudStorageR)

## make the bucket to save to
bucket_name <- paste("gcer", project, Sys.Date(), sep ="-")
bs <- gcs_list_buckets(project)

if(bucket_name %in% bs$name){
  message("Bucket found")
  b <- bucket_name
} else {
  b <- gcs_create_bucket(bucket_name, 
                         project, 
                         location = zone, 
                         storageClass = "STANDARD")
}
gcs_global_bucket(b)

```

This is what I get:

```
2017-11-11 10:16:20> No environment argument found, looked in GCS_AUTH_FILE
Warning message:
In googleAuthR::gar_attach_auto_auth("https://www.googleapis.com/auth/devstorage.full_control",  :
  travis_environment_var argument is now unsupported and does nothing

Request failed [400]. Retrying in 1.6 seconds...
Request failed [400]. Retrying in 1 seconds...
2017-11-11 10:27:34> Request Status Code: 400
Scopes: https://www.googleapis.com/auth/cloud-platform
Method: service_json
Error: API returned: Invalid Value
```

What am I missing?

**Comment by MarkEdmondson1234** [comment]
It looks like you are not setting the auth location for Google Cloud Storage, but for Google Compute Engine.  Its a seperate env value for each. `GCS_AUTH_FILE` != `GCE_AUTH_FILE`

I'd also recommend setting using an `.Renviron` file rather than within your code using `Sys.setenv`

**Comment by ignacio82** [comment]
How do you use an `.Renviron` instead of  `Sys.setenv`? Why is this better?

I tried this and it did not work:

    # Google Cloud Storage ----------------------------------------------------
    account_key <- "IMGoogle.json"
    Sys.setenv("GCS_AUTH_FILE" = account_key)
    library(googleCloudStorageR)
    
    ## make the bucket to save to
    
    bucket_name <- paste("gcer", project, Sys.Date(), sep ="-")
    bs <- gcs_list_buckets(project)
    
    if(bucket_name %in% bs$name){
      message("Bucket found")
      b <- bucket_name
    } else {
      b <- gcs_create_bucket(bucket_name, 
                             project, 
                             location = zone, 
                             storageClass = "STANDARD")
    }

```
Request failed [400]. Retrying in 1.6 seconds...
Request failed [400]. Retrying in 2.9 seconds...
2017-11-13 16:25:17> Request Status Code: 400
Scopes: https://www.googleapis.com/auth/devstorage.full_control
Method: service_json
 Show Traceback
 
 Rerun with Debug
 Error: API returned: Invalid Value 
```

Should I be using a different `.json` file than the one I use to start the VMs? If so where do I get that?

**Comment by MarkEdmondson1234** [comment]
Which API request is causing the 400 error?

**Comment by ignacio82** [comment]
Sorry, I'm not sure if I follow the question. I can create, stop, and start VMs without any problem. So, my guess is the issue is how I'm trying to use `googleCloudStorageR`.

**Comment by MarkEdmondson1234** [comment]
Which line in the code above :)

**Comment by MarkEdmondson1234** [comment]
Could you also run it with `options(googleAuthR.verbose = 1)`

**Comment by ignacio82** [comment]
This is what I get when I add that option:
https://gist.github.com/ignacio82/582261560236683552a86bcbc54e72ca

**Comment by MarkEdmondson1234** [comment]
I'm not sure why the bucket isn't being made as I can in the console, for now you can make one in the UI here:

https://console.cloud.google.com/storage/create-bucket

**Comment by ignacio82** [comment]
The guide still a bit over my head :(

I was able to create a bucket with the web ui. Then I did the following on my local machine:

1. I created a file `~/.Renviron` that has only this line on it: `GCS_SESSION_BUCKET="gcer-imgc-185017-2017-11-16"`

2. I creatd a file `~/..RProfile` that has two lines on it:
```
gcs_first 
gcs_last
```

3. I created a RStudio Project, that has some files and a `_gcssave.yaml` file with this line: `GCS_SESSION_BUCKET="gcer-imgc-185017-2017-11-16"`

4. I exited the project and nothing happens :-(

5. I loaded the project and nothing happened.

**Comment by MarkEdmondson1234** [comment]
Its still in development so the documentation is catching up :)

It all looks ok aside step 2 - setting up your `.Rprofile` 

Check out `?Startup` in R for an explanation on what happens on R startup anyhow, and also see the example in the help files of `?gcs_first()` that are also on website here http://code.markedmondson.me/googleCloudStorageR/reference/gcs_first.html

You need this in the `.RProfile` file, and for that file to also be in the correct location:

```
.First <- function(){
  cat("\n# Welcome Mark! Today is ", date(), "\n")

  ## will look for download if GCS_SESSION_BUCKET env arg set
  googleCloudStorageR::gcs_first()
}


.Last <- function(){
  # will only upload if a _gcssave.yaml in directory with bucketname
  googleCloudStorageR::gcs_last()
  message("\nGoodbye Mark at ", date(), "\n")
}
```

**Comment by ignacio82** [comment]
Am I running an old version of the package (0.3.0)?

```
> googleCloudStorageR::gcs_first()
Error: 'gcs_first' is not an exported object from 'namespace:googleCloudStorageR'
> googleCloudStorageR::gcs_last()
Error: 'gcs_last' is not an exported object from 'namespace:googleCloudStorageR'
```

**Comment by MarkEdmondson1234** [comment]
Yes, need GitHub version.

**Comment by ignacio82** [comment]
I think/hope I'm getting closer. I installed the GitHub version. Alas, I'm not there yet.

1. I think I'm not saving my .RProfile in the right place. I have it in my home directory but it does not load when I restart my R session:

![image](https://user-images.githubusercontent.com/1833309/32910027-2a5e4ec6-cad6-11e7-8c8f-7a69c8e40153.png)

2. If I load my project and I run `googleCloudStorageR::gcs_first()` by hand I get this:

```
> googleCloudStorageR::gcs_first()
Error in yaml$load_on_startup : $ operator is invalid for atomic vectors
```

**Comment by ignacio82** [comment]
Found one error. It should be .Rprofile instead of .RProfile (time for more coffee). Now when I load a project, it says:
```
n*** Successfully loaded .Rprofile ***n

# Welcome Ignacio! Today is  Thu Nov 16 19:08:01 2017 
Error in yaml$load_on_startup : $ operator is invalid for atomic vectors
[Workspace loaded from ~/projects/googlecloud/.RData]
```

**Comment by MarkEdmondson1234** [comment]
Nearly there :) Could I see your yaml file?  Can you load it using `yaml.load_file("_gcssave.yaml")` then show the response?

**Comment by ignacio82** [comment]
```
> yaml::yaml.load_file("_gcssave.yaml")
[1] "GCS_SESSION_BUCKET=\"gcer-imgc-185017-2017-11-16\""
```

**Comment by MarkEdmondson1234** [comment]
This is mine that works:

```yaml
## The GCS bucket to save/load R workspace from
bucket: gcer-xxxx-2017-08-11

## set to FALSE if you want to load on R session startup
load_on_startup: FALSE

## on first load, whether to look for a different directory on GCS than present getwd()
loaddir:

## regex to only save these files to GCS
pattern:


```

**Comment by MarkEdmondson1234** [comment]
It looks like you put in `_gcssave.yaml` what should be in the `.Renviron` instead. 

Three files to keep track of:

* `.Renviron` - environment arguments
* `.Rprofile`- startup behaviour
* `_gcssave.yaml` - per folder settings for what to save

**Comment by ignacio82** [comment]
Great! It is working! 

On the cloud RStudio server subsection. After step 2, I would add:

3. As you did on your local machine, you need to create an .Rprofile so `googleCloudStorageR` can load and save and load data. For example:

```
.First <- function(){
  cat("\n# Welcome Ignacio! Today is ", date(), "\n")

  ## will look for download if GCS_SESSION_BUCKET env arg set
  googleCloudStorageR::gcs_first()
}


.Last <- function(){
  # will only upload if a _gcssave.yaml in directory with bucketname
  googleCloudStorageR::gcs_last()
  message("\nGoodbye Ignacio at ", date(), "\n")
}

message("n*** Successfully loaded .Rprofile ***n")
```

**Comment by MarkEdmondson1234** [comment]
Great :) thanks for persisting, I used this thread to help the documentation a bit already - can you see if this is clearer?  I'll add above too. https://cloudyr.github.io/googleComputeEngineR/articles/persistent-rstudio.html

**Comment by ignacio82** [comment]
Yes, it is much easier to follow now. Thanks!

One more thing. I was thinking about why i need to create a .Rprofile everytime i create a new VM so `googleCloudStorageR` can load and save and load data. Moreover, the persistent ssh key does not work unless i do that. My guess is that the problem is that I'm using my own docker image instead of your `gcr.io/gcer-public/persistent-rstudio`. Is this correct? I tried to modify my dockerfile so it would upload the `.Rprofile` but it did not work as expected. All I did was to add this line to the end of my dockerfile:

```
# Adds .Rprofile
COPY R/.Rprofile $HOME/.Rprofile
```

**Comment by ignacio82** [comment]
I think i figured out by looking at your [dockerfile](https://github.com/cloudyr/googleComputeEngineR/blob/master/inst/dockerfiles/persistentRStudio/Dockerfile)

The image is compiling, so hopefully everything will workout

**Comment by ignacio82** [comment]
One more problem. When I load a project on my local computer I get this error

```
GCE auth didn't work, looking for GCS_AUTH_FILE
Error in gar_auto_auth(required_scopes, new_user = new_user, no_auto = no_auto,  : 
  GCS_AUTH_FILE specified in environment variables but file not found - 
           looked for IMGoogle.json and called from /home/ignacio/projects/IMBayesian
```

This does not happen on my `googlecloud` project because i have `IMGoogle.json` in that folder.

My guess is that the problem is with my `Renviron`

```
GCS_SESSION_BUCKET="gcer-imgc-185017-2017-11-16"
GCE_AUTH_FILE="IMGoogle.json"
GCE_DEFAULT_PROJECT_ID="imgc-185017"
GCE_DEFAULT_ZONE="us-east1-b"
GCS_AUTH_FILE="IMGoogle.json"
```

I tried changing `GCE_AUTH_FILE="IMGoogle.json"` to an absolute path to my home directory but that did not work (i do have a copy of the json file there)

**Comment by MarkEdmondson1234** [comment]
Yep, all the Dockerfile does differently is to add the [`Rprofile.site`](https://github.com/cloudyr/googleComputeEngineR/blob/master/inst/dockerfiles/persistentRStudio/Rprofile.site) file, which is a generic Rprofile file that will apply to all users
