### ISSUE TITLE
Can't connect to API, gce_global_project issues?

### ISSUE THREAD

**Issue by ctlamb** [cloudyr/googleComputeEngineR#85]
I have tried working through all the help files and videos but my Rstudio session just won't connect to the API.

My .Renviro seems to work OK, minus a couple warnings:

```
> library(googleComputeEngineR)
Setting scopes to https://www.googleapis.com/auth/cloud-platform
Successfully authenticated via /Users/clayton.lamb/Google Drive/Documents/University/R_Tricks/Cloud/test-24446eccb539.json
Set default project ID to 't-skyline-188419'
Set default zone to 'us-west1-a'
Warning messages:
1: In googleAuthR::gar_attach_auto_auth("https://www.googleapis.com/auth/cloud-platform",  :
  travis_environment_var argument is now unsupported and does nothing
2: In strptime(x, fmt, tz = "GMT") :
  unknown timezone 'zone/tz/2017c.1.0/zoneinfo/America/Edmonton'`
```

But I get weird behaviour when I get_project, and behaviour changes depending on the length of the name I give the project??

```
> gce_global_project("two")
Set default project name to 'two'
> gce_global_zone("us-west1-a")
Set default zone name to 'us-west1-a'
> gce_get_project()
Request failed [403]. Retrying in 1 seconds...
Request failed [403]. Retrying in 3 seconds...
2017-12-08 22:26:29> Request Status Code: 403
Scopes: https://www.googleapis.com/auth/cloud-platform
Method: service_json
Error: API returned: Project 335722831787 is not found and cannot be used for API calls. If it is recently created, enable Compute Engine API by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=335722831787 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.`

> gce_global_project("twoo")
Set default project name to 'twoo'
> gce_global_zone("us-west1-a")
Set default zone name to 'us-west1-a'
> gce_get_project()
Request failed [404]. Retrying in 1.4 seconds...
Request failed [404]. Retrying in 1.2 seconds...
2017-12-08 22:26:38> Request Status Code: 404
Scopes: https://www.googleapis.com/auth/cloud-platform
Method: service_json
Error: API returned: Failed to find project twoo`
```

I can confirm that Compute Engine API is enabled.

**Comment by MarkEdmondson1234** [comment]
You need to use your specific Google project ID ("t-skyline-188419" ?), not anything ("two"?) - I think you just need to read that from your Google Project then you are set.

**Comment by ctlamb** [comment]
Got it! Although it didn't like the #'s in the ID and threw an error, but the VM still booted. I tried to update package from GitHub but I'm on a Mac and it didn't like the Windows build there

2017-12-08 23:30:54> VM running
> vm
==Google Compute Engine Instance==

Name:                test
Created:             2017-12-08 15:30:09
Machine Type:        n1-highmem-2
Status:              RUNNING
Zone:                us-west1-a
External IP:         35.227.163.64
Disks: 
      deviceName       type       mode boot autoDelete
1 test-boot-disk PERSISTENT READ_WRITE TRUE       TRUE

**Comment by MarkEdmondson1234** [comment]
I think this was dealt with?  closing.
