### ISSUE TITLE
Am I running on VM right away? No login screen shows up

### ISSUE THREAD

**Issue by ctlamb** [cloudyr/googleComputeEngineR#86]
It is not immediately clear to me if any code I write after the "VM running" is received is then sent to the VM, OR, do I have to run gce_vm_start(vm)?

Regardless, both times I can see the 3 rsessions in for the 3 cores in parallel mclapply show up in my activity monitor, so this is then running on my local PC? Yet the VM is getting pinged too by the look of the graph.

Sorry I'm a bit confused where this is running..

```

> ##Load VM------------------------------------------------------------
> vm <- gce_vm(template="rstudio",
+              name="test",
+              username="X",
+              password="1234",
+              predefined_type="n1-highmem-2")
2017-12-09 22:11:28> VM running
> 
> 
> ##Load VM------------------------------------------------------------
> gce_vm_start(vm)
==Zone Operation start :  DONE
Started:  2017-12-09 14:11:38
Ended: 2017-12-09 14:11:38 
Operation complete in 0 secs 
> ##Start
> library(lme4)
Loading required package: Matrix
> library(parallel)
> 
> f <- function(x) {
+   lmer(Petal.Width ~  rnorm(nrow(iris),x) + Species + (1 | Species), data = iris)
+ }
> 
> system.time(save1 <- lapply(1:1000, f))
   user  system elapsed 
 19.583   0.094  19.721 
There were 18 warnings (use warnings() to see them)
> 
> system.time(save2 <- mclapply(1:1000, f, mc.cores=3))
   user  system elapsed 
  9.555   0.543  10.120 
> 
> 
> 
> gce_vm_stop(vm)
==Zone Operation stop :  PENDING
Started:  2017-12-09 14:13:24
```

**Comment by MarkEdmondson1234** [comment]
I've not used `library(parallel)` for multi-VM processing so not sure how you would set it up to use the VMs, I use `library(future)` following this guide here: 
https://cloudyr.github.io/googleComputeEngineR/articles/massive-parallel.html

If you want to stick to `parallel` you would need to ask their maintainers, looking at the code you have there is no mechanism for your functions to be sent to the VMs, it is running on your own local cores.  

I guess you need some kind of setup step where you create SSH keys (`gce_ssh_setup()`) and give the parallel library a way to record the VMs credentials you have made, such as  IPs/log in details.  That is what `googleComputeEngineR`'s  `future`integration takes care of, I would suggest that is a lot easier to use. 

The `gce_vm()` command is a shortcut that runs `gce_vm_create()` and `gce_vm_start()` so its up once its running.

**Comment by ctlamb** [comment]
OK, thanks, that helps a lot.

I will use the futures package from now on. BUT, just so I understand how the interface is working, can you help me understand why the parallel package version isn't working:

The code I have written right now only needs a single VM, so I had assumed that I had the VM up and running. The VM should have multiple cores, which are then split up by the mclapply call from parallels package. I should only need a single VM, and when I carry this out in full I would use a much larger VM with many more CPUs. 

Even simpler, what if I did the following, would this plot command go through my local cores or the VM?

```
> ##Load VM------------------------------------------------------------
> vm <- gce_vm(template="rstudio",
+              name="test",
+              username="X",
+              password="1234",
+              predefined_type="n1-highmem-2")
2017-12-09 22:11:28> VM running

##PLOT
plot(c(1:100),c(1:100))

```

**Comment by MarkEdmondson1234** [comment]
The VM is a physical machine running in the cloud, the `vm` object is just a reference to it.  

If you wanted to run anything on it, you would need to log in to that VM, which you can do via `gce_ssh_browser(vm)` which takes the details from the `vm` object and logs you in via Google's cloud SSH service. 

But you could similarly also login or send commands via `gce_ssh(vm, "echo foo")` (assuming SSH keys are setup, read the help files on how to do that)

**Comment by MarkEdmondson1234** [comment]
@ctlamb Is this issue sorted? Can it be closed?

**Comment by ctlamb** [comment]
Yes, closed. Thanks
