### ISSUE TITLE
Depend on futures for remote SSH?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [cloudyr/googleComputeEngineR#9]
http://www.jottr.org/2016/10/remote-processing-using-futures.html

**Comment by MarkEdmondson1234** [comment]
https://github.com/HenrikBengtsson/future/issues/101

**Comment by MarkEdmondson1234** [comment]
Working now via `gce_future_makeCluster` - launch it then just use `%<-%` to run that function asynchronously in the instance Docker:

``` r
library(googleComputeEngineR)
## dev version for now via source("http://callr.org/install#HenrikBengtsson/future@develop")
library(future) 

## make the instance
vm1 <- gce_vm_template("r-base", name = "r-future", predefined_type = "f1-micro")

## this function will probably will be internal eventually
gce_future_makeCluster(vm1)

## after docker file loaded, can send functions to cloud asynchronously

## check the platform:
si %<-% Sys.info()
print(si)
#> R version 3.3.1 (2016-06-21)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Debian GNU/Linux stretch/sid
#> etc...

## run R function on machine
f %<-% mean(1:199999)

## run your own functions
f <- function(x){paste(print("In Cloud > "), Sys.info())}
pp %<-% f()
pp
#> [1] "In Cloud >  Linux"                               "In Cloud >  4.4.4+"                             
#> [3] "In Cloud >  #1 SMP Wed Sep 28 11:11:37 PDT 2016" "In Cloud >  rdev"                               
#> [5] "In Cloud >  x86_64"                              "In Cloud >  unknown"                            
#> [7] "In Cloud >  root"                                "In Cloud >  root"    

# stop the instance again
gce_vm_stop(vm1)
#> ==Operation stop :  PENDING
#> Started:  2016-10-15 05:02:42
#> Connection to 104.155.115.49 closed by remote host.
```

It supports multiple clusters at a time, for parallel problems, by passing in more vms via `gce_future_makeCluster(list(vm1, vm2, vm3)` which is exciting.

**Comment by HenrikBengtsson** [comment]
This is good news.  (Moving my comment from https://github.com/HenrikBengtsson/future/issues/101 here):

I think a useful goal would be to provide an API such that the user can use the `plan()` function just like for all other types of futures, e.g.

``` r
vm <- gce_vm_template("r-base", name = "r-future", predefined_type = "f1-micro")
plan(gce, workers = vm)
```

and similarly for multiple remote GCE's, e.g.

``` r
plan(gce, workers = list(vm1, vm2, vm3))
```

I'll think about this and I'll try to do a PR with my suggestions.

Also, looking ahead, I can see how an similar API for Amazon Web Services (AWS) will show up too, e.g.

``` r
plan(aws, workers = list(vm1, vm2, vm3))
```

Now, there's nothing one couldn't mix'n'match different backends, so I could also imagine a smarter / more generic version of the already built in cluster futures such that one can simply do:

``` r
plan(cluster, workers = list(gce_vm1, aws_vm1, gce_vm2)) 
```

I'll think about it.  I can see several different approaches for solving the latter without adding dependencies to the future package itself.

**Comment by HenrikBengtsson** [comment]
See PR #10.  With that one can do:

``` r
cl <- as.cluster(vm)
plan(cluster, workers = cl)
```

and

``` r
vms <- list(vm1, vm2, vm3)
cl <- lapply(vms, FUN = as.cluster)
plan(cluster, workers = cl)
```

Note that, if you would to import the future package, i think the user could even use:

``` r
plan(cluster, workers = vm)
```

and

``` r
plan(cluster, workers = list(vm1, vm2, vm3))
```

**Comment by MarkEdmondson1234** [comment]
Thanks very much for this, I'll test it locally then merge.

I can't get my ssh related tests to run on travis at the moment, the SSH keys don't get recognised, so I'll be checking out how you do your tests.

There is an AWS library in this project here: [aws.ec2](https://github.com/cloudyr/aws.ec2) but doesn't use docker AFAIK, and also [analogsea](https://github.com/sckott/analogsea) for Digital Ocean that does. 

I plan to import future, so will just wait until you next update to CRAN.  I have no other deadline other than my enthusiasm, and am using this library at work so it will give time to try it out in real situations.  I hope to CRAN it myself when I get the testing on Travis sorted out and a few other template specific features to make it as easy as possible to use, but the basic functionality is all there now.

**Comment by HenrikBengtsson** [comment]
FYI, future 1.2.0 was just release on CRAN.

**Comment by MarkEdmondson1234** [comment]
Great, I'm nearing release myself too
