### ISSUE TITLE
gce_get_project() don´t work in googleComputeEngineR

### ISSUE THREAD

**Issue by manuelgomezrico** [cloudyr/googleComputeEngineR#94]
Hi
I have file .Renviron

GCE_AUTH_FILE="googlesearchconsole-f05500e7690a.json"
GCE_DEFAULT_PROJECT_ID="massive-boulder-195108"
GCE_DEFAULT_ZONE="europe-west1-b"

When I execute gce_get_project()

I have this error:

Request failed [403]. Retrying in 1.9 seconds...
Request failed [403]. Retrying in 1 seconds...
2018-02-15 16:05:44> Request Status Code: 403
Scopes: https://www.googleapis.com/auth/cloud-platform
Method: service_json
Error: API returned: Required 'compute.projects.get' permission for 'projects/massive-boulder-195108'

I don´t know why happens it?

Thanks

**Comment by MarkEdmondson1234** [comment]
Its not to do with the R package, but the authentication you are trying to do is not adequate yet.  You must configure your service account so that is has the correct permissions in your Google Cloud project. 

Have you followed this video guide here? https://cloudyr.github.io/googleComputeEngineR/articles/installation-and-authentication.html

**Comment by manuelgomezrico** [comment]
I saw it too, but when This afternoon I did this way I had a lot problems with permissions. For this reason after I tried with file .Renviron

Now I had tried it again, I now all right. Without this video I will be very crazy!!!

Thanks for share it

**Comment by abhijith-asok** [comment]
Hey,

I am facing the same problem. I did set up all the proper authentication but still gave the same error. Post that, I manually opened the .Renviron and fed in my specific project details, but it still refuses to connect. The Compute Engine API is up and running. Do you have anymore suggestions on how to identify the issue and resolve it? TIA!

**Comment by MarkEdmondson1234** [comment]
Hi @abhijith-asok - Open a new issue with the code you have tried and the error message.  If its exactly the same as above (`Error: API returned: Required 'compute.projects.get' permission for 'projects/massive-boulder-195108'`) then you must ensure the service account you are authenticating with has Google Compute Engine permissions - this is a GCP issue not the R library so you could try the demos with gcloud perhaps to get you started.
