### ISSUE TITLE
Installed packages are lost after restarting the VM session.

### ISSUE THREAD

**Issue by vikrant-sahu** [cloudyr/googleComputeEngineR#98]
When I restart my session I found that my installed packages are no longer available. What changes do I need to do so that the packages remain in the VM even after sign out.

**Comment by MarkEdmondson1234** [comment]
Please see this example and let me know how it goes https://cloudyr.github.io/googleComputeEngineR/articles/rstudio-team.html

**Comment by vikrant-sahu** [comment]
It's about coping the customising of one VM to another.
What I need is:
I install packages in R studio("install.packages()") which is installed on a VM instance.
Now  I quit from my session and stop the VM instance.
Next time when I start the same vm instance, I see that those packages are not there. And I have to reinstall all the packages which take a lot of time.

 But on my pc, once I install a package it remains forever.

**Comment by MarkEdmondson1234** [comment]
That is explained in the article above, also added to the FAQ https://cloudyr.github.io/googleComputeEngineR/articles/troubleshooting.html#my-changes-arent-saved-when-i-relaunch-my-rstudio-instance

**Comment by vasim07** [comment]
For non-docker users like us, this is a pain. 
We need to simply documentation on these.
